const api = require("../../utils/api");
Page({
  data: { id: "", lead: { childName: "", gender: "男", birthday: "2018-01-01", parentName: "", mobile: "", wechat: "", school: "", grade: "", interestedProgram: "", source: "朋友圈", intentionLevel: "B", ownerCoachId: "", ownerCoachName: "", remark: "" }, meta: { sources: [], intentions: [], coaches: [] }, genders: ["男", "女"], genderIndex: 0, sourceIndex: 1, intentionIndex: 1, coachIndex: 0, saving: false },
  async onLoad(options) { const meta = await api.call("getCrmMeta"); let lead = this.data.lead; if (options.id) lead = await api.call("getLead", { id: options.id }); const sourceIndex = Math.max(0, meta.sources.indexOf(lead.source)); const intentionIndex = Math.max(0, meta.intentions.indexOf(lead.intentionLevel)); const coachIndex = Math.max(0, meta.coaches.findIndex((item) => item.id === lead.ownerCoachId)); this.setData({ id: options.id || "", meta, lead, genderIndex: lead.gender === "女" ? 1 : 0, sourceIndex, intentionIndex, coachIndex }); wx.setNavigationBarTitle({ title: options.id ? "编辑招生线索" : "新增招生线索" }); },
  field(event) { this.setData({ [`lead.${event.currentTarget.dataset.key}`]: event.detail.value }); },
  gender(event) { const index = Number(event.detail.value); this.setData({ genderIndex: index, "lead.gender": this.data.genders[index] }); }, birthday(event) { this.setData({ "lead.birthday": event.detail.value }); },
  source(event) { const index = Number(event.detail.value); this.setData({ sourceIndex: index, "lead.source": this.data.meta.sources[index] }); }, intention(event) { const index = Number(event.detail.value); this.setData({ intentionIndex: index, "lead.intentionLevel": this.data.meta.intentions[index] }); }, coach(event) { const index = Number(event.detail.value), coach = this.data.meta.coaches[index]; this.setData({ coachIndex: index, "lead.ownerCoachId": coach.id, "lead.ownerCoachName": coach.name }); },
  async persist(continueDuplicate) { const lead = { ...this.data.lead, id: this.data.id || undefined }; await api.call("saveLead", { lead, continueDuplicate }); wx.showToast({ title: "线索已保存" }); setTimeout(() => wx.navigateBack(), 350); },
  async save() { if (this.data.saving) return; const lead = this.data.lead; if (!lead.childName.trim() || !lead.parentName.trim() || !/^1\d{10}$/.test(lead.mobile) || !lead.source) { wx.showToast({ title: "请完整填写必填项", icon: "none" }); return; } this.setData({ saving: true }); try { const duplicates = await api.call("checkLeadDuplicates", { id: this.data.id, mobile: lead.mobile }); if (duplicates.length) { const text = duplicates.map((item) => `${item.status}：${item.name}（${item.parentName}）`).join("\n"); wx.showModal({ title: "手机号已有相关记录", content: text, confirmText: "继续新建", cancelText: "取消", success: (result) => { if (result.confirm) this.persist(true); } }); } else await this.persist(false); } finally { this.setData({ saving: false }); } }
});
