const api = require("../../utils/api");

Page({
  data: { id: "", loading: true, saving: false, classes: [], classIndex: 0, plannedPreview: [], modes: ["开放报名", "梯队固定"], session: { classId: "", title: "", date: "", weekday: "", time: "", venue: "", coachName: "", trainingTheme: "", trainingFocus: "", trainingNote: "", focus: "", capacity: 20, enrollmentMode: "open", status: "published" } },
  async onLoad(options) {
    this.setData({ id: options.id || "" });
    try { const classes = await api.call("listClasses"); let session = this.data.session; if (options.id) session = await api.call("getSession", { id: options.id }); const classIndex = Math.max(0, classes.findIndex((item) => item.id === session.classId)); if (!session.classId && classes[0]) session = { ...session, classId: classes[0].id, title: classes[0].name, venue: classes[0].venue, coachName: classes[0].coachName }; const selected = classes[classIndex] || {}; const plannedPreview = (session.plannedCoaches || []).length ? session.plannedCoaches.map((row) => ({ name: row.coach.name, roleLabel: row.roleLabel })) : [{ name: (selected.headCoach || {}).name || selected.coachName, roleLabel: "主教练" }, ...(selected.assistantCoaches || []).map((coach) => ({ name: coach.name, roleLabel: "助理教练" }))].filter((row) => row.name); this.setData({ classes, classIndex, plannedPreview, session, loading: false }); } catch (error) { this.setData({ loading: false }); }
  },
  field(event) { this.setData({ [`session.${event.currentTarget.dataset.key}`]: event.detail.value }); },
  classChange(event) { const index = Number(event.detail.value); const item = this.data.classes[index]; const plannedPreview = [{ name: (item.headCoach || {}).name || item.coachName, roleLabel: "主教练" }, ...(item.assistantCoaches || []).map((coach) => ({ name: coach.name, roleLabel: "助理教练" }))].filter((row) => row.name); this.setData({ classIndex: index, plannedPreview, "session.classId": item.id, "session.title": item.name, "session.venue": item.venue, "session.coachName": item.coachName }); },
  dateChange(event) { const date = event.detail.value; const labels = ["周日", "周一", "周二", "周三", "周四", "周五", "周六"]; this.setData({ "session.date": date, "session.weekday": labels[new Date(`${date}T00:00:00`).getDay()] }); },
  modeChange(event) { this.setData({ "session.enrollmentMode": Number(event.detail.value) === 0 ? "open" : "fixed" }); },
  async save(forceConflict = false, conflictReason = "") { if (this.data.saving) return; this.setData({ saving: true }); try { const result = await api.call("saveSession", { session: { ...this.data.session, id: this.data.id || undefined, capacity: Number(this.data.session.capacity), forceConflict, conflictReason } }); if (result.confirmationRequired) { this.setData({ saving: false }); const messages = (result.conflicts || []).map((item) => item.message).join("\n"); return wx.showModal({ title: "发现排班冲突", content: messages, editable: true, placeholderText: "确认强制排课请填写原因", success: (modal) => { if (modal.confirm) this.save(true, modal.content); } }); } wx.showToast({ title: "课程已发布" }); setTimeout(() => wx.navigateBack(), 500); } finally { this.setData({ saving: false }); } }
});
