const api = require("../../utils/api");
const MODES = [{ key: "TIME", label: "按时间" }, { key: "COACH", label: "按教练" }, { key: "CLASS", label: "按班级" }, { key: "VENUE", label: "按场地" }];
function offset(value, days) { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }
function weekday(value) { return ["周日", "周一", "周二", "周三", "周四", "周五", "周六"][new Date(`${value}T12:00:00`).getDay()]; }
function group(items, mode) { const map = new Map(); const add = (key, label, item) => { if (!map.has(key)) map.set(key, { key, label, items: [] }); map.get(key).items.push(item); }; items.forEach((item) => { if (mode === "TIME") add(item.date, `${item.date.slice(5)} ${weekday(item.date)}`, item); else if (mode === "COACH") (item.coaches.length ? item.coaches : [{ coachId: "none", name: "未排教练" }]).forEach((coach) => add(coach.coachId || coach.name, coach.name, item)); else if (mode === "CLASS") add(item.classId || item.className, item.className, item); else add(item.venueId || item.venue, item.venue || "场地待定", item); }); return [...map.values()]; }
Page({
  data: { loading: true, error: "", modes: MODES, mode: "TIME", date: "", timetable: { items: [], stats: {}, conflicts: {}, filters: {} }, groups: [], classTypes: [{ id: "ALL", name: "全部类型" }, { id: "REGULAR", name: "普通班" }, { id: "ELITE", name: "精英队" }], classTypeIndex: 0, coachIndex: 0, classIndex: 0, venueIndex: 0, conflictType: "" },
  onLoad() { this.setData({ date: new Date().toISOString().slice(0, 10) }); }, onShow() { this.load(); }, onPullDownRefresh() { this.load(); },
  params() { const filters = this.data.timetable.filters || {}, coaches = [{ id: "", name: "全部教练" }, ...(filters.coaches || [])], classes = [{ id: "", name: "全部班级" }, ...(filters.classes || [])], venues = [{ id: "", name: "全部场地" }, ...(filters.venues || [])]; return { date: this.data.date, classType: this.data.classTypes[this.data.classTypeIndex].id, coachId: (coaches[this.data.coachIndex] || {}).id || "", classId: (classes[this.data.classIndex] || {}).id || "", venueId: (venues[this.data.venueIndex] || {}).id || "" }; },
  decorate(timetable) { const filters = timetable.filters || {}, coaches = [{ id: "", name: "全部教练" }, ...(filters.coaches || [])], classes = [{ id: "", name: "全部班级" }, ...(filters.classes || [])], venues = [{ id: "", name: "全部场地" }, ...(filters.venues || [])]; let items = (timetable.items || []).map((item) => ({ ...item, conflictCoach: (item.conflictTypes || []).includes("COACH"), conflictClass: (item.conflictTypes || []).includes("CLASS"), conflictVenue: (item.conflictTypes || []).includes("VENUE") })); if (this.data.conflictType) items = items.filter((item) => (item.conflictTypes || []).includes(this.data.conflictType)); this.setData({ timetable, coaches, classes, venues, groups: group(items, this.data.mode), loading: false }); },
  async load() { if (!this.data.date) return; this.setData({ loading: true, error: "" }); try { this.decorate(await api.call("getUnifiedTimetable", this.params())); } catch (error) { this.setData({ loading: false, error: "课表云端服务尚未更新，请部署新版 clubApi 后重试" }); } finally { wx.stopPullDownRefresh(); } },
  mode(event) { this.setData({ mode: event.currentTarget.dataset.key, conflictType: "" }, () => this.decorate(this.data.timetable)); },
  previous() { this.setData({ date: offset(this.data.timetable.startDate || this.data.date, -7) }, () => this.load()); }, next() { this.setData({ date: offset(this.data.timetable.startDate || this.data.date, 7) }, () => this.load()); }, current() { this.setData({ date: new Date().toISOString().slice(0, 10) }, () => this.load()); }, date(event) { this.setData({ date: event.detail.value }, () => this.load()); },
  classType(event) { this.setData({ classTypeIndex: Number(event.detail.value) }, () => this.load()); }, coach(event) { this.setData({ coachIndex: Number(event.detail.value) }, () => this.load()); }, clubClass(event) { this.setData({ classIndex: Number(event.detail.value) }, () => this.load()); }, venue(event) { this.setData({ venueIndex: Number(event.detail.value) }, () => this.load()); },
  conflict(event) { const type = event.currentTarget.dataset.type; this.setData({ conflictType: this.data.conflictType === type ? "" : type }, () => this.decorate(this.data.timetable)); },
  open(event) { if (event.currentTarget.dataset.type === "TRAINING") wx.navigateTo({ url: `/pages/session-detail/index?id=${event.currentTarget.dataset.id}` }); }
});
