const ACTIONS = new Set([
  "getFinanceMeta", "listProducts", "getProduct", "saveProduct", "toggleProduct", "listOrders", "getOrder", "createOrder", "cancelOrder", "recordPayment", "refundOrder", "adjustStudentLessons", "getRenewalCenter", "getFinanceDashboard", "getStudentFinance", "getFamilyFinance", "getClassFinance", "saveRenewalThresholds"
]);
const PRODUCT_TYPES = { LESSON_PACKAGE: "课时包", SEASON_PACKAGE: "学期/季度班", EVENT_FEE: "赛事费用", OTHER: "其他" };
const ORDER_STATUS = { PENDING: "待付款", PARTIAL_PAID: "部分付款", PAID: "已付款", CANCELLED: "已取消", REFUNDED: "已退款", PARTIAL_REFUNDED: "部分退款" };
const PAYMENT_METHODS = { WECHAT_TRANSFER: "微信转账", ALIPAY: "支付宝", CASH: "现金", BANK_TRANSFER: "银行转账", OTHER: "其他" };
function money(value) { return Math.round(Number(value || 0) * 100) / 100; }
function dateOnly(value) { return String(value || "").slice(0, 10); }
function monthOf(value) { return dateOnly(value).slice(0, 7); }

function createFinanceService(deps) {
  const { db, command, fetchAll, fetchByIds, publicDoc, nowText, requireRole, audit, assertStudentAccess, allowedStudentIds } = deps;
  let defaultsReady;
  async function ensureDefaults() {
    if (defaultsReady) return defaultsReady;
    defaultsReady = (async () => {
      const count = await db.collection("products").count();
      const rows = [
        { name: "一周一练课时包", productType: "LESSON_PACKAGE", lessonCount: 14, price: 1380, validityDays: 180 },
        { name: "一周两练课时包", productType: "LESSON_PACKAGE", lessonCount: 28, price: 1980, validityDays: 180 },
        { name: "2026秋季U8训练包", productType: "SEASON_PACKAGE", lessonCount: 30, price: 3600, validityDays: 150 },
        { name: "精英队季度课包", productType: "SEASON_PACKAGE", lessonCount: 20, price: 2800, validityDays: 120 },
        { name: "赛事综合服务费", productType: "EVENT_FEE", lessonCount: 0, price: 500, validityDays: 0 }
      ];
      if (!count.total) for (const item of rows) await db.collection("products").add({ data: { ...item, applicableClassTypes: [], applicableAgeGroups: [], active: true, description: "", createdAt: nowText(), updatedAt: nowText() } });
      const config = (await db.collection("financeSettings").where({ key: "renewal" }).limit(1).get()).data[0];
      if (!config) await db.collection("financeSettings").add({ data: { key: "renewal", renewalThresholds: [5, 3, 1], updatedAt: nowText() } });
    })();
    return defaultsReady;
  }
  async function settings() { const found = (await db.collection("financeSettings").where({ key: "renewal" }).limit(1).get()).data[0]; if (found) return found; const data = { key: "renewal", renewalThresholds: [5, 3, 1], updatedAt: nowText() }, added = await db.collection("financeSettings").add({ data }); return { ...data, _id: added._id }; }
  async function orderNumber() { const day = dateOnly(nowText()).replace(/-/g, ""), count = await db.collection("orders").where({ orderDay: day }).count(); return `NL${day}${String(count.total + 1).padStart(4, "0")}`; }
  async function canOrder(user, order) { await assertStudentAccess(user, order.studentId); return true; }
  async function decorate(order, user, detail = false) {
    const [studentResult, productResult] = await Promise.all([db.collection("students").doc(order.studentId).get().catch(() => ({ data: null })), db.collection("products").doc(order.productId).get().catch(() => ({ data: null }))]);
    const student = studentResult.data || {}, product = productResult.data || {}, value = { ...publicDoc(order), studentName: student.name || "", studentAvatarUrl: student.avatarUrl || "", remainingLessons: Number(student.remainingLessons || 0), product: { id: product._id, name: product.name, lessonCount: Number(order.lessonCount || product.lessonCount || 0) }, statusLabel: ORDER_STATUS[order.status] || order.status, outstandingAmount: Math.max(0, money(Number(order.payableAmount) - Number(order.paidAmount))), netReceived: money(Number(order.paidAmount) - Number(order.refundedAmount || 0)) };
    if (detail) { const [payments, refunds, ledger] = await Promise.all([fetchAll("payments", { orderId: order._id }), fetchAll("refunds", { orderId: order._id }), fetchAll("lessonLedger", { referenceType: "order", referenceId: order._id })]); value.payments = payments.map(publicDoc); value.refunds = refunds.map(publicDoc); value.lessonLedger = ledger.map(publicDoc); }
    return value;
  }
  async function listAllowedStudents(user) { const ids = await allowedStudentIds(user); if (ids === null) return fetchAll("students", { status: "active" }); return (await fetchByIds("students", ids)).filter((item) => item.status === "active"); }
  async function call(action, input, user) {
    await ensureDefaults();
    if (action === "getFinanceMeta") { const config = await settings(); return { productTypes: PRODUCT_TYPES, orderStatuses: ORDER_STATUS, paymentMethods: PAYMENT_METHODS, renewalThresholds: config.renewalThresholds }; }
    if (action === "listProducts") { if (user.role === "coach") throw new Error("教练无权查看产品价格"); let rows = await fetchAll("products"); if (user.role !== "admin") rows = rows.filter((item) => item.active); return rows.sort((a, b) => Number(b.active) - Number(a.active)).map((item) => ({ ...publicDoc(item), productTypeLabel: PRODUCT_TYPES[item.productType] || item.productType })); }
    if (action === "getProduct") { requireRole(user, ["admin"]); const item = (await db.collection("products").doc(input.id).get()).data; if (!item) throw new Error("产品不存在"); return { ...publicDoc(item), productTypeLabel: PRODUCT_TYPES[item.productType] || item.productType }; }
    if (action === "saveProduct") {
      requireRole(user, ["admin"]); const raw = input.product || {}, existing = raw.id ? (await db.collection("products").doc(raw.id).get()).data : null, data = { name: String(raw.name || "").trim(), productType: raw.productType || "LESSON_PACKAGE", lessonCount: Math.max(0, Number(raw.lessonCount || 0)), price: money(raw.price), applicableClassTypes: raw.applicableClassTypes || [], applicableAgeGroups: raw.applicableAgeGroups || [], validityDays: Math.max(0, Number(raw.validityDays || 0)), active: raw.active !== false, description: String(raw.description || ""), updatedAt: nowText() };
      if (!data.name || !(data.productType in PRODUCT_TYPES) || data.price < 0) throw new Error("产品信息不完整"); let id; if (existing) { id = existing._id; await db.collection("products").doc(id).update({ data }); await audit(user, Number(existing.price) !== data.price ? "UPDATE_PRODUCT_PRICE" : "UPDATE_PRODUCT", "product", id, { oldPrice: existing.price, newPrice: data.price, name: data.name }); } else { const added = await db.collection("products").add({ data: { ...data, createdAt: nowText() } }); id = added._id; await audit(user, "CREATE_PRODUCT", "product", id, { name: data.name, price: data.price }); } return { id };
    }
    if (action === "toggleProduct") { requireRole(user, ["admin"]); await db.collection("products").doc(input.id).update({ data: { active: Boolean(input.active), updatedAt: nowText() } }); await audit(user, "TOGGLE_PRODUCT", "product", input.id, { active: Boolean(input.active) }); return { ok: true }; }
    if (action === "listOrders") {
      if (user.role === "coach") throw new Error("教练无权查看订单金额"); let rows = await fetchAll("orders"); if (user.role === "parent") { const ids = new Set(await allowedStudentIds(user)); rows = rows.filter((item) => ids.has(item.studentId)); } if (input.studentId) { await assertStudentAccess(user, input.studentId); rows = rows.filter((item) => item.studentId === input.studentId); } if (input.status) rows = rows.filter((item) => item.status === input.status); const result = []; for (const row of rows.sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt)))) result.push(await decorate(row, user)); return result;
    }
    if (action === "getOrder") { if (user.role === "coach") throw new Error("教练无权查看订单金额"); const order = (await db.collection("orders").doc(input.id).get()).data; if (!order) throw new Error("订单不存在"); await canOrder(user, order); return decorate(order, user, true); }
    if (action === "createOrder") {
      requireRole(user, ["admin", "parent"]); await assertStudentAccess(user, input.studentId); const [student, product] = await Promise.all([db.collection("students").doc(input.studentId).get(), db.collection("products").doc(input.productId).get()]); if (!student.data || !product.data || !product.data.active && user.role !== "admin") throw new Error("学员或产品无效"); const discount = Math.max(0, money(input.discountAmount)); if (discount > Number(product.data.price)) throw new Error("优惠金额不能超过原价"); const createdAt = nowText(), orderNo = await orderNumber(), orderDay = dateOnly(createdAt).replace(/-/g, ""), data = { orderNo, orderDay, parentUserId: student.data.ownerParentUserId || "", studentId: student.data._id, productId: product.data._id, productName: product.data.name, productType: product.data.productType, lessonCount: Number(product.data.lessonCount || 0), originalAmount: money(product.data.price), discountAmount: discount, payableAmount: money(Number(product.data.price) - discount), paidAmount: 0, refundedAmount: 0, status: "PENDING", source: input.source || (user.role === "parent" ? "PARENT_RENEWAL" : "ADMIN_ORDER"), crmLeadId: input.crmLeadId || "", createdBy: user._id, createdAt, updatedAt: createdAt }; const added = await db.collection("orders").add({ data }); await audit(user, "CREATE_ORDER", "order", added._id, { orderNo, studentId: data.studentId, productId: data.productId, payableAmount: data.payableAmount }); return { id: added._id, orderNo };
    }
    if (action === "cancelOrder") { requireRole(user, ["admin"]); const order = (await db.collection("orders").doc(input.id).get()).data; if (!order || !["PENDING", "PARTIAL_PAID"].includes(order.status) || Number(order.paidAmount || 0) > 0) throw new Error("当前订单不可取消"); const reason = String(input.reason || "管理员取消"); await db.collection("orders").doc(input.id).update({ data: { status: "CANCELLED", cancelledAt: nowText(), cancelReason: reason, updatedAt: nowText() } }); await audit(user, "CANCEL_ORDER", "order", input.id, { orderNo: order.orderNo, reason }); return { ok: true }; }
    if (action === "recordPayment") {
      requireRole(user, ["admin"]); const amount = money(input.amount), key = String(input.idempotencyKey || input.transactionRef || "").trim(), transactionRef = String(input.transactionRef || "").trim(); if (!(amount > 0)) throw new Error("收款金额必须大于0"); if (key) { let duplicate = (await db.collection("payments").where({ idempotencyKey: key }).limit(1).get()).data[0]; if (!duplicate && transactionRef) duplicate = (await db.collection("payments").where({ transactionRef }).limit(1).get()).data[0]; if (duplicate) return { id: duplicate._id, duplicate: true }; }
      let paymentId, orderResult;
      await db.runTransaction(async (transaction) => {
        const order = (await transaction.collection("orders").doc(input.orderId).get()).data; if (!order || ["CANCELLED", "REFUNDED"].includes(order.status)) throw new Error("当前订单不能收款"); const outstanding = money(Number(order.payableAmount) - Number(order.paidAmount)); if (amount > outstanding) throw new Error("收款金额不能超过待收金额"); const receivedAt = input.receivedAt || nowText(), payment = { orderId: order._id, amount, paymentMethod: input.paymentMethod || "WECHAT_TRANSFER", transactionRef: String(input.transactionRef || ""), idempotencyKey: key || `${order._id}-${receivedAt}-${amount}`, receivedBy: user._id, receivedAt, remark: String(input.remark || ""), createdAt: nowText() }, added = await transaction.collection("payments").add({ data: payment }); paymentId = added._id; const paidAmount = money(Number(order.paidAmount) + amount), paid = paidAmount >= Number(order.payableAmount), update = { paidAmount, status: paid ? "PAID" : "PARTIAL_PAID", updatedAt: nowText() };
        if (paid) { update.paidAt = receivedAt; if (Number(order.lessonCount || 0) > 0 && !order.lessonGrantedAt) { const student = (await transaction.collection("students").doc(order.studentId).get()).data, balance = Number(student.remainingLessons || 0) + Number(order.lessonCount); await transaction.collection("students").doc(order.studentId).update({ data: { remainingLessons: balance, totalLessons: Number(student.totalLessons || 0) + Number(order.lessonCount), updatedAt: nowText() } }); const ledger = await transaction.collection("lessonLedger").add({ data: { studentId: order.studentId, type: "PACKAGE_PURCHASE", delta: Number(order.lessonCount), balanceAfter: balance, referenceType: "order", referenceId: order._id, orderNo: order.orderNo, note: `${order.productName}购买到账（订单${order.orderNo}）`, createdAt: nowText(), operatorId: user._id } }); update.lessonGrantedAt = nowText(); update.lessonLedgerId = ledger._id; } }
        await transaction.collection("orders").doc(order._id).update({ data: update }); orderResult = { ...order, ...update };
      }); await audit(user, "RECORD_PAYMENT", "payment", paymentId, { orderId: input.orderId, amount, paymentMethod: input.paymentMethod }); return { id: paymentId, order: await decorate(orderResult, user, true) };
    }
    if (action === "refundOrder") {
      requireRole(user, ["admin"]); const amount = money(input.amount), lessonAdjustment = Math.max(0, Number(input.lessonAdjustment || 0)), reason = String(input.reason || "").trim(); if (!(amount > 0) || !reason) throw new Error("请填写有效退款金额和原因"); let refundId, orderResult;
      await db.runTransaction(async (transaction) => { const order = (await transaction.collection("orders").doc(input.orderId).get()).data; if (!order || !["PAID", "PARTIAL_REFUNDED"].includes(order.status)) throw new Error("当前订单不可退款"); const refundable = money(Number(order.paidAmount) - Number(order.refundedAmount || 0)); if (amount > refundable) throw new Error("退款金额超过可退金额"); const student = (await transaction.collection("students").doc(order.studentId).get()).data; if (lessonAdjustment > Number(student.remainingLessons || 0) && !input.overrideNegativeBalance) throw new Error("退款扣减课时将导致余额不足，请确认强制调整"); const refund = { orderId: order._id, studentId: order.studentId, amount, lessonAdjustment, reason, processedBy: user._id, processedAt: nowText(), createdAt: nowText() }, added = await transaction.collection("refunds").add({ data: refund }); refundId = added._id; if (lessonAdjustment) { const balance = Number(student.remainingLessons || 0) - lessonAdjustment; await transaction.collection("students").doc(order.studentId).update({ data: { remainingLessons: balance, updatedAt: nowText() } }); const ledger = await transaction.collection("lessonLedger").add({ data: { studentId: order.studentId, type: "REFUND_ADJUSTMENT", delta: -lessonAdjustment, balanceAfter: balance, referenceType: "order", referenceId: order._id, orderNo: order.orderNo, refundId, note: `订单${order.orderNo}退款课时调整：${reason}`, createdAt: nowText(), operatorId: user._id } }); await transaction.collection("refunds").doc(refundId).update({ data: { lessonLedgerId: ledger._id } }); } const refundedAmount = money(Number(order.refundedAmount || 0) + amount), update = { refundedAmount, status: refundedAmount >= Number(order.paidAmount) ? "REFUNDED" : "PARTIAL_REFUNDED", updatedAt: nowText() }; await transaction.collection("orders").doc(order._id).update({ data: update }); orderResult = { ...order, ...update }; }); await audit(user, "REFUND_ORDER", "refund", refundId, { orderId: input.orderId, amount, lessonAdjustment, reason }); return { id: refundId, order: await decorate(orderResult, user, true) };
    }
    if (action === "adjustStudentLessons") { requireRole(user, ["admin"]); const delta = Number(input.delta || 0), reason = String(input.reason || "").trim(); if (!delta || !reason) throw new Error("课时调整必须填写数量和原因"); let ledgerId, balanceAfter; await db.runTransaction(async (transaction) => { const student = (await transaction.collection("students").doc(input.studentId).get()).data; if (!student) throw new Error("学员不存在"); balanceAfter = Number(student.remainingLessons || 0) + delta; if (balanceAfter < 0 && !input.overrideNegativeBalance) throw new Error("调整后课时将为负数，请确认强制调整"); await transaction.collection("students").doc(input.studentId).update({ data: { remainingLessons: balanceAfter, totalLessons: delta > 0 ? Number(student.totalLessons || 0) + delta : Number(student.totalLessons || 0), updatedAt: nowText() } }); const added = await transaction.collection("lessonLedger").add({ data: { studentId: input.studentId, type: delta > 0 ? "MANUAL_BONUS" : "MANUAL_DEDUCTION", delta, balanceAfter, referenceType: "manualAdjustment", referenceId: `${user._id}-${Date.now()}`, note: reason, createdAt: nowText(), operatorId: user._id } }); ledgerId = added._id; }); await audit(user, delta > 0 ? "MANUAL_GRANT_LESSONS" : "MANUAL_DEDUCT_LESSONS", "lessonLedger", ledgerId, { studentId: input.studentId, delta, reason }); return { id: ledgerId, balanceAfter }; }
    if (action === "saveRenewalThresholds") { requireRole(user, ["admin"]); const thresholds = [...new Set((input.thresholds || []).map(Number).filter((item) => item >= 0))].sort((a, b) => b - a); if (!thresholds.length) throw new Error("请至少设置一个续费阈值"); const config = await settings(); await db.collection("financeSettings").doc(config._id).update({ data: { renewalThresholds: thresholds, updatedAt: nowText() } }); await audit(user, "UPDATE_RENEWAL_THRESHOLDS", "financeSettings", config._id, { thresholds }); return { ok: true }; }
    if (action === "getRenewalCenter") { requireRole(user, ["admin", "coach"]); const config = await settings(), max = Math.max(...config.renewalThresholds), students = (await listAllowedStudents(user)).filter((item) => Number(item.remainingLessons || 0) <= max), classes = await fetchAll("classes"), rows = students.map((student) => ({ id: student._id, name: student.name, initial: student.name ? student.name[0] : "学", avatarUrl: student.avatarUrl || "", remainingLessons: Number(student.remainingLessons || 0), classNames: classes.filter((item) => (student.classIds || []).includes(item._id)).map((item) => item.name).join("、"), guardianName: user.role === "admin" ? student.guardianName : undefined, level: Number(student.remainingLessons || 0) <= 0 ? "EMPTY" : Number(student.remainingLessons || 0) <= 1 ? "CRITICAL" : "LOW" })).sort((a, b) => a.remainingLessons - b.remainingLessons); let recentOrders = []; if (user.role === "admin") { const orders = (await fetchAll("orders")).filter((item) => ["PAID", "PARTIAL_REFUNDED"].includes(item.status)).sort((a, b) => String(b.paidAt).localeCompare(String(a.paidAt))).slice(0, 10); for (const item of orders) recentOrders.push(await decorate(item, user)); } return { thresholds: config.renewalThresholds, students: rows, recentOrders }; }
    if (action === "getStudentFinance") { if (user.role === "coach") throw new Error("教练无权查看财务金额"); await assertStudentAccess(user, input.studentId); const [studentResult, orders, ledger] = await Promise.all([db.collection("students").doc(input.studentId).get(), fetchAll("orders", { studentId: input.studentId }), fetchAll("lessonLedger", { studentId: input.studentId })]), decorated = []; for (const item of orders.sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt)))) decorated.push(await decorate(item, user)); const paid = orders.reduce((sum, item) => sum + Number(item.paidAmount || 0), 0), refunded = orders.reduce((sum, item) => sum + Number(item.refundedAmount || 0), 0); return { student: { ...publicDoc(studentResult.data), remainingLessons: studentResult.data.remainingLessons }, summary: { orderAmount: money(orders.reduce((sum, item) => sum + Number(item.payableAmount || 0), 0)), paidAmount: money(paid), refundedAmount: money(refunded), netReceived: money(paid - refunded) }, orders: decorated, lessonLedger: ledger.sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt))).map(publicDoc) }; }
    if (action === "getFamilyFinance") { requireRole(user, ["admin"]); const students = await fetchAll("students", { ownerParentUserId: input.parentUserId }), result = []; for (const student of students) { const orders = await fetchAll("orders", { studentId: student._id }); result.push({ id: student._id, name: student.name, remainingLessons: student.remainingLessons, orderCount: orders.length, paidAmount: money(orders.reduce((sum, item) => sum + Number(item.paidAmount || 0), 0)), refundedAmount: money(orders.reduce((sum, item) => sum + Number(item.refundedAmount || 0), 0)) }); } return { parentUserId: input.parentUserId, students: result }; }
    if (action === "getClassFinance") { requireRole(user, ["admin"]); const [clubClass, members, config] = await Promise.all([db.collection("classes").doc(input.classId).get(), fetchAll("classMembers", { classId: input.classId, status: "ACTIVE" }), settings()]), ids = members.map((item) => item.studentId), students = await fetchByIds("students", ids), orders = (await fetchAll("orders")).filter((item) => ids.includes(item.studentId)), month = input.month || monthOf(nowText()); return { classId: input.classId, className: clubClass.data.name, formalMembers: students.length, newMembers: members.filter((item) => monthOf(item.joinedAt) === month).length, renewedStudents: new Set(orders.filter((item) => monthOf(item.paidAt) === month && ["PAID", "PARTIAL_REFUNDED"].includes(item.status)).map((item) => item.studentId)).size, lowBalanceStudents: students.filter((item) => Number(item.remainingLessons || 0) <= Math.max(...config.renewalThresholds)).length, receivedAmount: money(orders.reduce((sum, item) => sum + Number(item.paidAmount || 0) - Number(item.refundedAmount || 0), 0)) }; }
    if (action === "getFinanceDashboard") { requireRole(user, ["admin"]); const day = dateOnly(input.date || nowText()), month = day.slice(0, 7), [payments, refunds, orders, students, config] = await Promise.all([fetchAll("payments"), fetchAll("refunds"), fetchAll("orders"), fetchAll("students", { status: "active" }), settings()]), pending = orders.filter((item) => ["PENDING", "PARTIAL_PAID"].includes(item.status)); return { metrics: { todayReceived: money(payments.filter((item) => dateOnly(item.receivedAt) === day).reduce((sum, item) => sum + Number(item.amount), 0)), monthReceived: money(payments.filter((item) => monthOf(item.receivedAt) === month).reduce((sum, item) => sum + Number(item.amount), 0)), monthOrders: orders.filter((item) => monthOf(item.createdAt) === month).length, monthRefunded: money(refunds.filter((item) => monthOf(item.processedAt) === month).reduce((sum, item) => sum + Number(item.amount), 0)), pendingOrders: pending.length, pendingAmount: money(pending.reduce((sum, item) => sum + Math.max(0, Number(item.payableAmount) - Number(item.paidAmount)), 0)), renewalStudents: students.filter((item) => Number(item.remainingLessons || 0) <= Math.max(...config.renewalThresholds)).length }, recentPayments: payments.sort((a, b) => String(b.receivedAt).localeCompare(String(a.receivedAt))).slice(0, 8).map(publicDoc), recentRefunds: refunds.sort((a, b) => String(b.processedAt).localeCompare(String(a.processedAt))).slice(0, 8).map(publicDoc) }; }
    throw new Error("未知财务操作");
  }
  return { handles: (action) => ACTIONS.has(action), call, ensureDefaults };
}

module.exports = { createFinanceService, PRODUCT_TYPES, ORDER_STATUS, PAYMENT_METHODS };
