const CATEGORIES = { TECHNICAL: "技术", TACTICAL: "战术", ATHLETIC: "运动能力", MATCH: "比赛能力", DEVELOPMENT: "训练表现" };
const SCORE_LABELS = { 1: "需要重点培养", 2: "正在建立", 3: "基本掌握", 4: "表现良好", 5: "表现突出" };
const METRICS = {
  TECHNICAL: [["DRIBBLE_TOUCH", "球感"], ["DRIBBLING", "带球"], ["PASSING", "传球"], ["RECEIVING", "接球"], ["SHOOTING", "射门"], ["ONE_V_ONE_ATTACK", "1V1进攻"], ["ONE_V_ONE_DEFENSE", "1V1防守"], ["WEAK_FOOT", "弱势脚使用"]],
  TACTICAL: [["OFF_BALL_MOVEMENT", "无球跑动"], ["SPATIAL_AWARENESS", "空间意识"], ["ATTACK_DECISION", "进攻选择"], ["DEFENSIVE_POSITIONING", "防守站位"], ["TRANSITION", "攻防转换"], ["TEAM_PLAY", "团队配合"]],
  ATHLETIC: [["COORDINATION", "协调性"], ["AGILITY", "灵敏性"], ["SPEED", "速度表现"], ["BALANCE", "平衡能力"], ["ENDURANCE", "耐力表现"]],
  MATCH: [["MATCH_ENGAGEMENT", "比赛投入度"], ["EXECUTION", "执行能力"], ["DUEL_DECISION", "对抗处理"], ["CHANCE_CREATION", "机会创造"], ["DEFENSIVE_CONTRIBUTION", "防守贡献"], ["TEAMWORK", "团队合作"]],
  DEVELOPMENT: [["FOCUS", "训练专注"], ["MOTIVATION", "训练积极性"], ["LEARNING", "学习理解"], ["TEAMWORK", "团队合作"], ["DISCIPLINE", "纪律执行"]]
};
const DAILY_TAGS = ["积极主动", "控球表现好", "1V1表现积极", "传球意识好", "比赛投入", "需要加强专注", "需要提高弱势脚", "需要提高防守意识"];
const ACTIONS = new Set(["getGrowthMeta", "listAssessmentTemplates", "saveAssessmentTemplate", "listAssessmentRounds", "createAssessmentRound", "getAssessmentRound", "savePlayerAssessment", "publishAssessmentRound", "getGrowthProfile", "getSessionEvaluationRoster", "saveTrainingEvaluation", "batchAddTrainingTag", "saveMatchRecord", "saveGrowthEvent", "getEliteGrowthSummary"]);

function round(value) { return Math.round(Number(value || 0) * 10) / 10; }
function dimensions(weights) { return Object.keys(METRICS).flatMap((category) => METRICS[category].map(([metricKey, metricName]) => ({ category, metricKey, metricName, weight: weights[category], enabled: true }))); }
function calculate(template, scores) { const categoryScores = {}; Object.keys(CATEGORIES).forEach((category) => { const rows = scores.filter((item) => item.category === category); if (rows.length) categoryScores[category] = round(rows.reduce((sum, item) => sum + Number(item.score), 0) / rows.length); }); const weights = template.categoryWeights || {}; let weighted = 0, total = 0; Object.keys(categoryScores).forEach((category) => { const weight = Number(weights[category] || 1); weighted += categoryScores[category] * weight; total += weight; }); return { categoryScores, overallScore: round(total ? weighted / total : 0) }; }

function createGrowthService({ db, command, fetchAll, fetchByIds, publicDoc, nowText, todayText, requireRole, audit, assertStudentAccess, coachScope }) {
  let defaultsReady;
  async function ensureDefaults() { if (defaultsReady) return defaultsReady; defaultsReady = (async () => { const count = await db.collection("assessmentTemplates").count(); if (count.total) return; const templates = [{ name: "南联 U5-U6 成长测评", ageGroup: "U5-U6", weights: { TECHNICAL: 35, TACTICAL: 10, ATHLETIC: 25, MATCH: 10, DEVELOPMENT: 20 } }, { name: "南联 U7-U8 成长测评", ageGroup: "U7-U8", weights: { TECHNICAL: 35, TACTICAL: 20, ATHLETIC: 20, MATCH: 15, DEVELOPMENT: 10 } }]; for (const item of templates) await db.collection("assessmentTemplates").add({ data: { name: item.name, ageGroup: item.ageGroup, assessmentType: "STAGE", categoryWeights: item.weights, dimensions: dimensions(item.weights), active: true, createdAt: nowText(), updatedAt: nowText() } }); })(); return defaultsReady; }
  async function studentAccess(user, studentId, options = {}) {
    if (!studentId) throw new Error("请选择学员");
    if (user.role === "admin") return { current: true };
    if (user.role === "parent") { await assertStudentAccess(user, studentId); return { current: true }; }
    try { await coachScope.assertStudentAccess(user, studentId); return { current: true }; }
    catch (error) {
      if (!options.allowOwnHistory || error.code !== "COACH_STUDENT_SCOPE_FORBIDDEN") throw error;
      const coachId = coachScope.coachPrincipalId(user);
      const [assessment, feedback, match] = await Promise.all([
        db.collection("playerAssessments").where({ studentId, assessedBy: coachId }).limit(1).get(),
        db.collection("feedback").where({ studentId, updatedBy: coachId }).limit(1).get(),
        db.collection("playerMatchRecords").where({ studentId, createdBy: coachId }).limit(1).get(),
      ]);
      if (!assessment.data.length && !feedback.data.length && !match.data.length) throw error;
      return { current: false, ownHistoryOnly: true };
    }
  }
  async function classAccess(user, classId) { if (user.role === "admin") return; if (user.role === "coach") return coachScope.assertClassAccess(user, classId); throw new Error("无权管理该班级"); }
  function visible(item, user) { return user.role !== "parent" || item.visibility !== "STAFF_ONLY"; }
  async function growthProfile(user, studentId) {
    const access = await studentAccess(user, studentId, { allowOwnHistory: true }); const student = (await db.collection("students").doc(studentId).get()).data; if (!student || student.status !== "active") throw new Error("学员不存在或已停用");
    let memberships = await fetchAll("classMembers", { studentId, status: "ACTIVE" }); let classes = await fetchByIds("classes", memberships.map((item) => item.classId));
    const coachId = user.role === "coach" ? coachScope.coachPrincipalId(user) : "";
    const assignedClassIds = user.role === "coach" ? new Set(await coachScope.assignedClassIds(user)) : null;
    if (assignedClassIds) { memberships = memberships.filter((item) => assignedClassIds.has(item.classId)); classes = classes.filter((item) => assignedClassIds.has(item._id)); }
    let assessments = (await db.collection("playerAssessments").where({ studentId }).limit(100).get()).data.filter((item) => user.role !== "parent" || item.published && visible(item, user));
    if (user.role === "coach") assessments = assessments.filter((item) => item.assessedBy === coachId || access.current && assignedClassIds.has(item.classId));
    assessments = assessments.sort((a, b) => String(a.assessmentDate).localeCompare(String(b.assessmentDate)));
    assessments = assessments.map((item) => ({ ...publicDoc(item), categoryRows: Object.keys(CATEGORIES).map((key) => ({ key, name: CATEGORIES[key], score: (item.categoryScores || {})[key] || 0 })) }));
    const latest = assessments[assessments.length - 1] || null, previous = assessments[assessments.length - 2] || null;
    const comparisons = Object.keys(CATEGORIES).map((key) => { const score = latest ? Number(latest.categoryScores[key] || 0) : 0, before = previous ? Number(previous.categoryScores[key] || 0) : 0, delta = round(score - before); return { key, name: CATEGORIES[key], score, delta, direction: delta > 0 ? "up" : delta < 0 ? "down" : "flat", deltaText: delta > 0 ? `↑ ${delta}` : delta < 0 ? `↓ ${Math.abs(delta)}` : "→" }; });
    const [feedbackRows, matchRows, eventRows, attendanceRows] = await Promise.all([db.collection("feedback").where({ studentId }).orderBy("createdAt", "desc").limit(30).get(), db.collection("playerMatchRecords").where({ studentId }).orderBy("matchDate", "desc").limit(30).get(), db.collection("playerGrowthEvents").where({ studentId }).orderBy("eventDate", "desc").limit(50).get(), db.collection("attendance").where({ studentId }).orderBy("date", "desc").limit(100).get()]);
    let feedbackRaw = feedbackRows.data.filter((item) => visible(item, user)), matchRaw = matchRows.data.filter((item) => visible(item, user)), attendanceRaw = attendanceRows.data;
    if (user.role === "coach") {
      const feedbackSessions = await fetchByIds("sessions", feedbackRaw.map((item) => item.sessionId));
      const sessionClass = new Map(feedbackSessions.map((item) => [item._id, item.classId]));
      feedbackRaw = feedbackRaw.filter((item) => item.updatedBy === coachId || access.current && assignedClassIds.has(sessionClass.get(item.sessionId)));
      matchRaw = matchRaw.filter((item) => item.createdBy === coachId || access.current && item.classId && assignedClassIds.has(item.classId));
      attendanceRaw = attendanceRaw.filter((item) => access.current && assignedClassIds.has(item.classId));
    }
    const feedback = feedbackRaw.map(publicDoc), matches = matchRaw.map(publicDoc);
    const generated = [...assessments.map((item) => ({ id: `timeline-${item.id}`, eventType: "ASSESSMENT", title: item.assessmentName, description: `综合能力 ${item.overallScore}`, eventDate: item.assessmentDate })), ...feedback.map((item) => ({ id: `timeline-${item.id}`, eventType: "TRAINING", title: "训练评价", description: item.content, eventDate: String(item.createdAt).slice(0, 10) })), ...matches.map((item) => ({ id: `timeline-${item.id}`, eventType: "MATCH", title: `${item.teamName} vs ${item.opponent}`, description: item.coachComment, eventDate: item.matchDate }))];
    const month = todayText().slice(0, 7), monthRows = attendanceRaw.filter((item) => String(item.date).slice(0, 7) === month); const joined = memberships.map((item) => item.joinedAt).filter(Boolean).sort()[0] || student.registrationDate || ""; const months = joined ? Math.max(0, Math.floor((Date.now() - new Date(joined.replace(/-/g, "/")).getTime()) / 2629800000)) : 0;
    let events = eventRows.data.filter((item) => visible(item, user)); if (user.role === "coach") events = events.filter((item) => item.createdBy === coachId || access.current && item.classId && assignedClassIds.has(item.classId));
    return { student: { ...(user.role === "coach" ? coachScope.coachStudentView(student) : publicDoc(student)), classNames: classes.map((item) => item.name), trainingDuration: `${Math.floor(months / 12)}年${months % 12}个月`, latestTrainingDate: attendanceRaw[0] ? attendanceRaw[0].date : "暂无" }, access: user.role === "coach" ? { editable: access.current, historicalOnly: !access.current } : undefined, attendance: { total: monthRows.length, present: monthRows.filter((item) => item.status === "present").length, leave: monthRows.filter((item) => item.status === "leave").length, absent: monthRows.filter((item) => item.status === "absent").length }, latestAssessment: latest, previousAssessment: previous, comparisons, assessments, trends: assessments.slice(-6).map((item) => ({ date: item.assessmentDate, label: String(item.assessmentDate).slice(5), overall: item.overallScore, ...(item.categoryScores || {}) })), feedback: feedback.slice(0, 10), matches: matches.slice(0, 10), events: [...events.map(publicDoc), ...generated].sort((a, b) => String(b.eventDate).localeCompare(String(a.eventDate))).slice(0, 30) };
  }
  async function call(action, input, user) {
    await ensureDefaults();
    if (action === "getGrowthMeta") return { categories: CATEGORIES, scoreLabels: SCORE_LABELS, metrics: METRICS, dailyTags: DAILY_TAGS, templates: (await fetchAll("assessmentTemplates", { active: true })).map(publicDoc) };
    if (action === "listAssessmentTemplates") { requireRole(user, ["admin", "coach"]); return (await fetchAll("assessmentTemplates")).map(publicDoc); }
    if (action === "saveAssessmentTemplate") { requireRole(user, ["admin"]); const raw = input.template || {}; if (!raw.name || !raw.ageGroup || !(raw.dimensions || []).length) throw new Error("测评模板信息不完整"); const data = { ...raw, active: raw.active !== false, updatedAt: nowText() }; delete data.id; let id = raw.id; if (id) await db.collection("assessmentTemplates").doc(id).update({ data }); else { const added = await db.collection("assessmentTemplates").add({ data: { ...data, createdAt: nowText() } }); id = added._id; } await audit(user, "saveAssessmentTemplate", "assessmentTemplate", id, raw.name); return { id }; }
    if (action === "listAssessmentRounds") { requireRole(user, ["admin", "coach"]); let rows = await fetchAll("assessmentRounds"); if (user.role === "coach") { const ids = new Set(await coachScope.assignedClassIds(user)); rows = rows.filter((item) => ids.has(item.classId)); } const members = await fetchAll("classMembers", { status: "ACTIVE" }), assessments = await fetchAll("playerAssessments"); return rows.map((item) => { const expected = members.filter((row) => row.classId === item.classId).length, completed = assessments.filter((row) => row.roundId === item._id && row.status === "COMPLETED").length; return { ...publicDoc(item), expected, completed, progressText: `${completed} / ${expected}` }; }).sort((a, b) => String(b.assessmentDate).localeCompare(String(a.assessmentDate))); }
    if (action === "createAssessmentRound") { requireRole(user, ["admin"]); const template = (await db.collection("assessmentTemplates").doc(input.assessmentTemplateId).get()).data; if (!template || !template.active) throw new Error("请选择有效测评模板"); const data = { name: String(input.name || "").trim(), classId: input.classId, ageGroup: input.ageGroup || template.ageGroup, assessmentTemplateId: template._id, assessmentDate: input.assessmentDate, coachId: input.coachId || "", coachName: input.coachName || "", status: "DRAFT", createdAt: nowText(), updatedAt: nowText() }; if (!data.name || !data.classId || !data.assessmentDate) throw new Error("阶段测评信息不完整"); const added = await db.collection("assessmentRounds").add({ data }); await audit(user, "createAssessmentRound", "assessmentRound", added._id, data.name); return { id: added._id }; }
    if (action === "getAssessmentRound") { requireRole(user, ["admin", "coach"]); const item = (await db.collection("assessmentRounds").doc(input.id).get()).data; await classAccess(user, item.classId); const [template, members, assessments] = await Promise.all([db.collection("assessmentTemplates").doc(item.assessmentTemplateId).get(), fetchAll("classMembers", { classId: item.classId, status: "ACTIVE" }), fetchAll("playerAssessments", { roundId: item._id })]); const students = await fetchByIds("students", members.map((row) => row.studentId)); return { ...publicDoc(item), template: publicDoc(template.data), students: students.map((student) => { const assessment = assessments.find((row) => row.studentId === student._id); return { ...(user.role === "coach" ? coachScope.coachStudentView(student) : publicDoc(student)), assessmentId: assessment ? assessment._id : "", assessmentStatus: assessment ? assessment.status : "NOT_STARTED" }; }), completed: assessments.filter((row) => row.status === "COMPLETED").length, expected: members.length }; }
    if (action === "savePlayerAssessment") { requireRole(user, ["admin", "coach"]); const roundItem = (await db.collection("assessmentRounds").doc(input.roundId).get()).data; await classAccess(user, roundItem.classId); const member = (await db.collection("classMembers").where({ classId: roundItem.classId, studentId: input.studentId, status: "ACTIVE" }).limit(1).get()).data[0]; if (!member) { const error = new Error("只能评价本班正式成员"); error.code = "COACH_STUDENT_SCOPE_FORBIDDEN"; throw error; } const template = (await db.collection("assessmentTemplates").doc(roundItem.assessmentTemplateId).get()).data, valid = new Set(template.dimensions.filter((item) => item.enabled).map((item) => item.metricKey)); const scores = (input.scores || []).filter((item) => valid.has(item.metricKey)).map((item) => ({ ...item, score: Math.max(1, Math.min(5, Number(item.score))) })); if (!scores.length) throw new Error("请至少填写一项评分"); const computed = calculate(template, scores), existing = (await db.collection("playerAssessments").where({ roundId: roundItem._id, studentId: input.studentId }).limit(1).get()).data[0], now = nowText(); const coachId = user.role === "coach" ? coachScope.coachPrincipalId(user) : user._id; if (user.role === "coach" && existing && existing.assessedBy && existing.assessedBy !== coachId) throw new Error("不能修改其他教练创建的阶段评价"); const data = { roundId: roundItem._id, studentId: input.studentId, classId: roundItem.classId, assessmentTemplateId: template._id, assessmentType: "STAGE", assessmentName: roundItem.name, assessmentDate: roundItem.assessmentDate, scores, ...computed, strengths: input.strengths || [], developmentAreas: input.developmentAreas || [], coachComment: String(input.coachComment || ""), coachMessage: String(input.coachMessage || ""), mediaAttachments: input.mediaAttachments || [], status: input.complete ? "COMPLETED" : "DRAFT", visibility: input.visibility || "STAFF_ONLY", published: false, assessedBy: coachId, assessedByName: user.name, revision: existing ? Number(existing.revision || 1) + 1 : 1, updatedAt: now, updatedBy: coachId }; let id; if (existing) { id = existing._id; await db.collection("playerAssessments").doc(id).update({ data }); } else { const added = await db.collection("playerAssessments").add({ data: { ...data, createdAt: now } }); id = added._id; } await audit(user, existing ? "updatePlayerAssessment" : "savePlayerAssessment", "playerAssessment", id, { studentId: input.studentId, roundId: roundItem._id, revision: data.revision }); return { id, overallScore: data.overallScore, status: data.status }; }
    if (action === "publishAssessmentRound") { requireRole(user, ["admin"]); const item = (await db.collection("assessmentRounds").doc(input.id).get()).data, members = await fetchAll("classMembers", { classId: item.classId, status: "ACTIVE" }), rows = await fetchAll("playerAssessments", { roundId: item._id, status: "COMPLETED" }); if (!members.length || rows.length < members.length) throw new Error(`尚未完成全部测评（${rows.length}/${members.length}）`); const now = nowText(); for (const row of rows) await db.collection("playerAssessments").doc(row._id).update({ data: { published: true, visibility: row.visibility === "STAFF_ONLY" ? "STAFF_ONLY" : "PARENT_VISIBLE", updatedAt: now } }); await db.collection("assessmentRounds").doc(item._id).update({ data: { status: "COMPLETED", publishedAt: now, publishedBy: user._id, updatedAt: now } }); await audit(user, "publishAssessmentRound", "assessmentRound", item._id, `${rows.length}名球员`); return { ok: true, published: rows.length }; }
    if (action === "getGrowthProfile") return growthProfile(user, input.studentId);
    if (action === "getSessionEvaluationRoster") { requireRole(user, ["admin", "coach"]); const session = (await db.collection("sessions").doc(input.sessionId).get()).data; if (user.role === "coach") await coachScope.assertSessionAccess(user, session); const members = await fetchAll("classMembers", { classId: session.classId, status: "ACTIVE" }), students = await fetchByIds("students", members.map((item) => item.studentId)), feedback = await fetchAll("feedback", { sessionId: session._id }); return { session: publicDoc(session), students: students.map((student) => ({ ...(user.role === "coach" ? coachScope.coachStudentView(student) : publicDoc(student)), evaluation: publicDoc(feedback.find((item) => item.studentId === student._id)) || null })) }; }
    if (action === "saveTrainingEvaluation") { requireRole(user, ["admin", "coach"]); const session = (await db.collection("sessions").doc(input.sessionId).get()).data; if (user.role === "coach") await coachScope.assertSessionAccess(user, session); if (!(await db.collection("classMembers").where({ classId: session.classId, studentId: input.studentId, status: "ACTIVE" }).limit(1).get()).data.length) { const error = new Error("只能评价授权班级正式成员"); error.code = "COACH_STUDENT_SCOPE_FORBIDDEN"; throw error; } const coachId = user.role === "coach" ? coachScope.coachPrincipalId(user) : user._id; const existing = (await db.collection("feedback").where({ sessionId: session._id, studentId: input.studentId }).limit(1).get()).data[0]; if (user.role === "coach" && existing && existing.updatedBy && existing.updatedBy !== coachId) throw new Error("不能修改其他教练创建的训练评价"); const data = { sessionId: session._id, studentId: input.studentId, evaluationType: "DAILY", trainingStatus: Math.max(1, Math.min(5, Number(input.trainingStatus || 3))), highlights: String(input.highlights || ""), developmentAreas: String(input.developmentAreas || ""), coachName: user.name, rating: Math.max(1, Math.min(5, Number(input.trainingStatus || 3))), tags: input.tags || [], content: String(input.coachComment || ""), visibility: input.visibility || "STAFF_ONLY", mediaAttachments: input.mediaAttachments || [], updatedAt: nowText(), updatedBy: coachId }; let id; if (existing) { id = existing._id; await db.collection("feedback").doc(id).update({ data }); } else { const added = await db.collection("feedback").add({ data: { ...data, createdAt: nowText() } }); id = added._id; } await audit(user, existing ? "updateTrainingEvaluation" : "saveTrainingEvaluation", "feedback", id, { studentId: input.studentId, sessionId: session._id, visibility: data.visibility }); return { id }; }
    if (action === "batchAddTrainingTag") { requireRole(user, ["admin", "coach"]); const roster = await call("getSessionEvaluationRoster", { sessionId: input.sessionId }, user), allowed = new Set(roster.students.map((item) => item.id)), tag = String(input.tag || "").trim(), coachId = user.role === "coach" ? coachScope.coachPrincipalId(user) : user._id; if (!tag) throw new Error("请选择评价标签"); for (const studentId of input.studentIds || []) { if (!allowed.has(studentId)) throw new Error("批量名单包含非本班成员"); const existing = (await db.collection("feedback").where({ sessionId: input.sessionId, studentId }).limit(1).get()).data[0]; if (user.role === "coach" && existing && existing.updatedBy && existing.updatedBy !== coachId) throw new Error("不能修改其他教练创建的训练评价"); if (existing) await db.collection("feedback").doc(existing._id).update({ data: { tags: [...new Set([...(existing.tags || []), tag])], updatedAt: nowText(), updatedBy: coachId } }); else await db.collection("feedback").add({ data: { sessionId: input.sessionId, studentId, evaluationType: "DAILY", trainingStatus: 3, highlights: "", developmentAreas: "", coachName: user.name, rating: 3, tags: [tag], content: "", visibility: "STAFF_ONLY", createdAt: nowText(), updatedAt: nowText(), updatedBy: coachId } }); } await audit(user, "batchAddTrainingTag", "session", input.sessionId, { studentIds: input.studentIds || [], tag }); return { count: (input.studentIds || []).length }; }
    if (action === "saveMatchRecord") { requireRole(user, ["admin", "coach"]); await studentAccess(user, input.studentId); if (!input.matchDate || !input.opponent || !input.teamName) throw new Error("比赛记录信息不完整"); const data = { ...input, goals: Number(input.goals || 0), assists: Number(input.assists || 0), minutesPlayed: Number(input.minutesPlayed || 0), coachRating: Math.max(1, Math.min(5, Number(input.coachRating || 3))), visibility: input.visibility || "STAFF_ONLY", createdBy: user.role === "coach" ? coachScope.coachPrincipalId(user) : user._id, createdAt: nowText(), updatedAt: nowText() }; delete data.id; const added = await db.collection("playerMatchRecords").add({ data }); await audit(user, "saveMatchRecord", "playerMatchRecord", added._id, { studentId: input.studentId, matchDate: input.matchDate }); return { id: added._id }; }
    if (action === "saveGrowthEvent") { requireRole(user, ["admin"]); if (!input.studentId || !input.title || !input.eventDate) throw new Error("成长事件信息不完整"); const data = { ...input, visibility: input.visibility || "STAFF_ONLY", createdBy: user._id, createdAt: nowText() }; delete data.id; const added = await db.collection("playerGrowthEvents").add({ data }); await audit(user, "saveGrowthEvent", "playerGrowthEvent", added._id, { studentId: input.studentId, visibility: data.visibility }); return { id: added._id }; }
    if (action === "getEliteGrowthSummary") { requireRole(user, ["admin", "coach"]); const result = await growthProfile(user, input.studentId); return { latestAssessment: result.latestAssessment, trends: result.trends, recentFeedback: result.feedback.slice(0, 3), matches: result.matches.slice(0, 3), attendance: result.attendance }; }
    throw new Error("未知成长档案操作");
  }
  return { handles: (action) => ACTIONS.has(action), call, ensureDefaults, constants: { CATEGORIES, SCORE_LABELS, METRICS, DAILY_TAGS } };
}

module.exports = { createGrowthService };
