const ACTIONS=new Set(["getTrainingMeta","getResearchDashboard","listCurriculums","saveCurriculum","archiveCurriculum","listWeeklyTrainingPlans","getWeeklyTrainingPlan","saveWeeklyTrainingPlan","confirmWeeklyTrainingPlan","saveSessionTrainingInfo","getSessionTrainingInfo","getSessionTrainingPlan","getCoachWorkbench","getTrainingHistory"]);
const TRAINING_TOPICS={BALL_MASTERY:"球感",DRIBBLING:"带球",PASSING:"传球",RECEIVING:"接球",SHOOTING:"射门",ONE_V_ONE_ATTACK:"1V1进攻",ONE_V_ONE_DEFENSE:"1V1防守",TWO_V_ONE:"2V1",SPATIAL_AWARENESS:"空间意识",TRANSITION:"攻防转换",TEAM_PLAY:"团队配合",COORDINATION:"协调",MATCH_PLAY:"比赛"};
const STATUS_LABELS={DRAFT:"草稿",CONFIRMED:"已确认",COMPLETED:"已完成"};
function createTrainingService(deps){const{db,fetchAll,publicDoc,nowText,requireRole,audit,assertStudentAccess}=deps;let ready;
async function ensureDefaults(){if(ready)return ready;ready=(async()=>{const count=await db.collection("curriculums").count();if(!count.total)for(const item of [{name:"南联U5-U6训练大纲",ageGroup:"U5-U6",classType:"REGULAR",objectives:["建立足球兴趣","发展球感与协调"],trainingTopics:["BALL_MASTERY","COORDINATION","DRIBBLING","SHOOTING","ONE_V_ONE_ATTACK","MATCH_PLAY"],description:"球感、协调、带球、射门、简单1V1和游戏化比赛。"},{name:"南联U7-U8训练大纲",ageGroup:"U7-U8",classType:"REGULAR",objectives:["建立控球基础","培养主动进攻与空间意识"],trainingTopics:["BALL_MASTERY","DRIBBLING","PASSING","RECEIVING","ONE_V_ONE_ATTACK","TWO_V_ONE","SHOOTING","SPATIAL_AWARENESS","TRANSITION","MATCH_PLAY"],description:"控球、带球、传接球、1V1、2V1、射门、空间意识、攻防转换和小场比赛。"},{name:"南联U8精英队训练大纲",ageGroup:"U8",classType:"ELITE",objectives:["提高比赛决策","发展团队配合与位置意识"],trainingTopics:["ONE_V_ONE_ATTACK","TRANSITION","SPATIAL_AWARENESS","TEAM_PLAY","MATCH_PLAY"],description:"高强度1V1、攻防转换、比赛决策、团队配合、位置意识和比赛应用。"}])await db.collection("curriculums").add({data:{...item,active:true,createdBy:"admin",createdAt:nowText(),updatedAt:nowText()}})})();return ready}
function staff(user){requireRole(user,["admin","coach"])}function canClass(user,id){if(user.role!=="admin"&&!(user.classIds||[]).includes(id))throw new Error("无权管理该班训练")}function curriculumView(item){return{...publicDoc(item),topicNames:(item.trainingTopics||[]).map(k=>TRAINING_TOPICS[k]||k)}}
async function planView(item){const [clubClass,curriculum]=await Promise.all([db.collection("classes").doc(item.classId).get().catch(()=>({data:{}})),item.curriculumId?db.collection("curriculums").doc(item.curriculumId).get().catch(()=>({data:{}})):Promise.resolve({data:{}})]);return{...publicDoc(item),className:clubClass.data.name||"",ageGroup:clubClass.data.ageGroup||"",curriculumName:curriculum.data.name||"",statusLabel:STATUS_LABELS[item.status]||item.status}}
async function call(action,input,user){await ensureDefaults();
if(action==="getTrainingMeta")return{trainingTopics:TRAINING_TOPICS,statuses:STATUS_LABELS};
if(action==="listCurriculums"){staff(user);return(await fetchAll("curriculums")).filter(i=>user.role==="admin"||i.active).map(curriculumView)}
if(action==="saveCurriculum"){requireRole(user,["admin"]);const r=input.curriculum||{},data={name:String(r.name||"").trim(),ageGroup:String(r.ageGroup||""),classType:r.classType==="ELITE"?"ELITE":"REGULAR",objectives:r.objectives||[],trainingTopics:r.trainingTopics||[],description:String(r.description||""),active:r.active!==false,updatedAt:nowText()};if(!data.name||!data.ageGroup||!data.trainingTopics.length)throw new Error("训练大纲信息不完整");let id=r.id;if(id)await db.collection("curriculums").doc(id).update({data});else{const added=await db.collection("curriculums").add({data:{...data,createdBy:user._id,createdAt:nowText()}});id=added._id}await audit(user,"SAVE_CURRICULUM","curriculum",id,{name:data.name});return{id}}
if(action==="archiveCurriculum"){requireRole(user,["admin"]);await db.collection("curriculums").doc(input.id).update({data:{active:false,updatedAt:nowText()}});await audit(user,"ARCHIVE_CURRICULUM","curriculum",input.id,{});return{ok:true}}
if(action==="listWeeklyTrainingPlans"){staff(user);let rows=await fetchAll("weeklyTrainingPlans");if(user.role==="coach")rows=rows.filter(i=>(user.classIds||[]).includes(i.classId));if(input.classId)rows=rows.filter(i=>i.classId===input.classId);if(input.coachId)rows=rows.filter(i=>i.coachId===input.coachId);if(input.status)rows=rows.filter(i=>i.status===input.status);const result=[];for(const item of rows.sort((a,b)=>String(b.weekStart).localeCompare(String(a.weekStart))))result.push(await planView(item));return result}
if(action==="getWeeklyTrainingPlan"){staff(user);const item=(await db.collection("weeklyTrainingPlans").doc(input.id).get()).data;canClass(user,item.classId);return planView(item)}
if(action==="saveWeeklyTrainingPlan"){staff(user);const r=input.plan||{},old=r.id?(await db.collection("weeklyTrainingPlans").doc(r.id).get()).data:null,classId=r.classId||(old||{}).classId;canClass(user,classId);const data={classId,coachId:r.coachId||(old||{}).coachId||user._id,coachName:r.coachName||(old||{}).coachName||user.name,weekStart:r.weekStart||"",weekEnd:r.weekEnd||"",mainTheme:String(r.mainTheme||"").trim(),themeKey:r.themeKey||"",trainingFocus:r.trainingFocus||[],curriculumId:r.curriculumId||"",status:r.status||(old||{}).status||"DRAFT",meetingNote:String(r.meetingNote||""),updatedBy:user._id,updatedAt:nowText()};if(!data.weekStart||!data.weekEnd||!data.mainTheme||!data.trainingFocus.length)throw new Error("周训练计划信息不完整");let id=r.id;if(id)await db.collection("weeklyTrainingPlans").doc(id).update({data});else{const added=await db.collection("weeklyTrainingPlans").add({data:{...data,createdAt:nowText()}});id=added._id}await audit(user,"SAVE_WEEKLY_TRAINING_PLAN","weeklyTrainingPlan",id,{classId,status:data.status});return{id}}
if(action==="confirmWeeklyTrainingPlan"){staff(user);const item=(await db.collection("weeklyTrainingPlans").doc(input.id).get()).data;canClass(user,item.classId);const data={status:input.completed?"COMPLETED":"CONFIRMED",meetingNote:input.meetingNote===undefined?item.meetingNote:String(input.meetingNote),updatedBy:user._id,updatedAt:nowText()};await db.collection("weeklyTrainingPlans").doc(input.id).update({data});await audit(user,"CONFIRM_WEEKLY_TRAINING_PLAN","weeklyTrainingPlan",input.id,{status:data.status});return{ok:true,status:data.status}}
if(action==="saveSessionTrainingInfo"){staff(user);const session=(await db.collection("sessions").doc(input.sessionId).get()).data;canClass(user,session.classId);const data={trainingTheme:String(input.trainingTheme||"").trim(),trainingThemeKey:input.trainingThemeKey||"",trainingFocus:input.trainingFocus||[],trainingNote:String(input.trainingNote||""),weeklyTrainingPlanId:input.weeklyTrainingPlanId||session.weeklyTrainingPlanId||"",updatedAt:nowText(),updatedBy:user._id};if(!data.trainingTheme||!data.trainingFocus.length)throw new Error("请填写训练主题和训练重点");await db.collection("sessions").doc(input.sessionId).update({data});await audit(user,"SAVE_SESSION_TRAINING_INFO","session",input.sessionId,{trainingTheme:data.trainingTheme});return{ok:true}}
if(action==="getSessionTrainingInfo"||action==="getSessionTrainingPlan"){const session=(await db.collection("sessions").doc(input.sessionId).get()).data;if(!session)throw new Error("课程不存在");const weekly=session.weeklyTrainingPlanId?(await db.collection("weeklyTrainingPlans").doc(session.weeklyTrainingPlanId).get().catch(()=>({data:null}))).data:null,value={session:{id:session._id,title:session.title,date:session.date,time:session.time,classId:session.classId},trainingTheme:session.trainingTheme||session.focus||"",trainingThemeKey:session.trainingThemeKey||"",trainingFocus:session.trainingFocus||[],trainingNote:session.trainingNote||"",weeklyTrainingPlanId:session.weeklyTrainingPlanId||"",weeklyTheme:weekly?weekly.mainTheme:"",trainingPurpose:session.trainingPurpose||""};if(user.role==="parent"){await assertStudentAccess(user,input.studentId);delete value.trainingNote;return value}staff(user);canClass(user,session.classId);value.weeklyPlan=weekly?await planView(weekly):null;return value}
if(action==="getCoachWorkbench"){staff(user);let sessions=await fetchAll("sessions");if(user.role==="coach")sessions=sessions.filter(i=>(user.classIds||[]).includes(i.classId));const [members,leaves]=await Promise.all([fetchAll("classMembers",{status:"ACTIVE"}),fetchAll("leaveRequests",{status:"approved"})]);return{date:input.date||nowText().slice(0,10),sessions:sessions.sort((a,b)=>`${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`)).map(s=>({...publicDoc(s),memberCount:members.filter(i=>i.classId===s.classId).length,leaveCount:leaves.filter(i=>i.sessionId===s._id).length,trainingTheme:s.trainingTheme||s.focus||"待填写",trainingFocusText:(s.trainingFocus||[]).join(" / ")}))}}
if(action==="getTrainingHistory"){await assertStudentAccess(user,input.studentId);const [attendance,sessions]=await Promise.all([fetchAll("attendance",{studentId:input.studentId,status:"present"}),fetchAll("sessions")]),ids=new Set(attendance.map(i=>i.sessionId)),counts={};sessions.filter(i=>ids.has(i._id)).forEach(i=>{const key=i.trainingThemeKey||i.trainingTheme||i.focus;if(key)counts[key]=(counts[key]||0)+1});return{days:Number(input.days||30),totalSessions:Object.values(counts).reduce((s,n)=>s+n,0),tags:Object.keys(counts).map(key=>({key,name:TRAINING_TOPICS[key]||key,count:counts[key]})).sort((a,b)=>b.count-a.count)}}
if(action==="getResearchDashboard"){staff(user);let plans=await fetchAll("weeklyTrainingPlans"),sessions=await fetchAll("sessions");if(user.role==="coach"){plans=plans.filter(i=>(user.classIds||[]).includes(i.classId));sessions=sessions.filter(i=>(user.classIds||[]).includes(i.classId))}const decorated=[];for(const item of plans)decorated.push(await planView(item));return{metrics:{curriculums:(await db.collection("curriculums").where({active:true}).count()).total,weeklyPlans:plans.length,confirmedPlans:plans.filter(i=>i.status==="CONFIRMED").length,sessions:sessions.length,filledSessions:sessions.filter(i=>i.trainingTheme&&(i.trainingFocus||[]).length).length},weeklyPlans:decorated}}
throw new Error("未知训练管理操作")}
return{handles:a=>ACTIONS.has(a),call,ensureDefaults}}
module.exports={createTrainingService,TRAINING_TOPICS};
