const api = require("../../utils/api");
Page({
  data: { role: "admin", orders: [], students: [], products: [], alerts: [], studentId: "", studentIndex: 0, productIndex: 0, discountAmount: "0", showForm: false, loading: true, submitting: false },
  onLoad(options) { this.setData({ studentId: options.studentId || "" }); }, onShow() { this.load(); },
  async load() {
    this.setData({ loading: true }); const context = await api.call("getContext");
    if (context.user.role === "coach") { const center = await api.call("getRenewalCenter"); this.setData({ role: "coach", alerts: center.students, loading: false }); return; }
    const [students, products] = await Promise.all([api.call("listStudents"), api.call("listProducts")]), remembered = this.data.studentId || getApp().globalData.activeStudentId || wx.getStorageSync("activeStudentId"), studentId = context.user.role === "parent" && students.some((item) => item.id === remembered) ? remembered : this.data.studentId || (context.user.role === "parent" && students[0] ? students[0].id : ""), studentIndex = Math.max(0, students.findIndex((item) => item.id === studentId)), orders = await api.call("listOrders", { studentId: context.user.role === "parent" ? studentId : "" }); let alerts = []; if (context.user.role === "admin") alerts = (await api.call("getRenewalCenter")).students;
    this.setData({ role: context.user.role, students, products: products.filter((item) => item.active), orders, alerts, studentId, studentIndex, loading: false });
  },
  studentChange(event) { const studentIndex = Number(event.detail.value), student = this.data.students[studentIndex]; this.setData({ studentIndex, studentId: student.id }); if (this.data.role === "parent") { getApp().globalData.activeStudentId = student.id; wx.setStorageSync("activeStudentId", student.id); this.load(); } }, product(event) { this.setData({ productIndex: Number(event.detail.value) }); }, discount(event) { this.setData({ discountAmount: event.detail.value }); }, openForm(event) { const studentId = event.currentTarget.dataset.student || this.data.studentId, studentIndex = Math.max(0, this.data.students.findIndex((item) => item.id === studentId)); this.setData({ showForm: true, studentIndex }); }, closeForm() { if (!this.data.submitting) this.setData({ showForm: false }); },
  async create() { const student = this.data.students[this.data.studentIndex], product = this.data.products[this.data.productIndex]; if (!student || !product) return wx.showToast({ title: "请选择学员和产品", icon: "none" }); this.setData({ submitting: true }); try { const result = await api.call("createOrder", { studentId: student.id, productId: product.id, discountAmount: this.data.role === "admin" ? Number(this.data.discountAmount || 0) : 0 }); wx.showToast({ title: "订单已创建" }); this.setData({ showForm: false }); wx.navigateTo({ url: `/pages/order-detail/index?id=${result.id}` }); } finally { this.setData({ submitting: false }); } },
  order(event) { wx.navigateTo({ url: `/pages/order-detail/index?id=${event.currentTarget.dataset.id}` }); }, products() { wx.navigateTo({ url: "/pages/products/index" }); }, finance() { wx.navigateTo({ url: "/pages/finance-dashboard/index" }); }
});
