const api = require("../../utils/api");
Page({
  data: { roundId: "", studentId: "", index: 0, detail: null, student: null, rows: [], strengthsText: "", developmentText: "", coachComment: "", coachMessage: "", visibility: "STAFF_ONLY", saving: false, loading: true, scoreOptions: [1, 2, 3, 4, 5] },
  async onLoad(options) { this.setData({ roundId: options.roundId || "", studentId: options.studentId || "", index: Number(options.index || 0) }); const [detail, profile] = await Promise.all([api.call("getAssessmentRound", { id: options.roundId }), api.call("getGrowthProfile", { studentId: options.studentId })]); const existing = (profile.assessments || []).find((item) => item.roundId === options.roundId), student = detail.students.find((item) => item.id === options.studentId), labels = { TECHNICAL: "技术", TACTICAL: "战术", ATHLETIC: "运动能力", MATCH: "比赛能力", DEVELOPMENT: "训练表现" }; const rows = detail.template.dimensions.filter((item) => item.enabled).map((item) => ({ ...item, categoryName: labels[item.category], score: Number(((existing || {}).scores || []).find((score) => score.metricKey === item.metricKey)?.score || 3), scoreIndex: Number(((existing || {}).scores || []).find((score) => score.metricKey === item.metricKey)?.score || 3) - 1 })); this.setData({ detail, student, rows, strengthsText: ((existing || {}).strengths || []).join("、"), developmentText: ((existing || {}).developmentAreas || []).join("、"), coachComment: (existing || {}).coachComment || "", coachMessage: (existing || {}).coachMessage || "", visibility: (existing || {}).visibility || "STAFF_ONLY", loading: false }); },
  score(event) { const index = Number(event.currentTarget.dataset.index), scoreIndex = Number(event.detail.value); this.setData({ rows: this.data.rows.map((item, itemIndex) => itemIndex === index ? { ...item, scoreIndex, score: this.data.scoreOptions[scoreIndex] } : item) }); },
  field(event) { this.setData({ [event.currentTarget.dataset.key]: event.detail.value }); }, visible(event) { this.setData({ visibility: event.detail.value ? "PARENT_VISIBLE" : "STAFF_ONLY" }); }, draft() { this.save(false); }, complete() { this.save(true); },
  async save(complete) { if (this.data.saving) return; this.setData({ saving: true }); try { await api.call("savePlayerAssessment", { roundId: this.data.roundId, studentId: this.data.studentId, scores: this.data.rows.map(({ category, metricKey, metricName, score }) => ({ category, metricKey, metricName, score })), strengths: this.data.strengthsText.split(/[，,、]/).map((item) => item.trim()).filter(Boolean), developmentAreas: this.data.developmentText.split(/[，,、]/).map((item) => item.trim()).filter(Boolean), coachComment: this.data.coachComment, coachMessage: this.data.coachMessage, visibility: this.data.visibility, complete }); wx.showToast({ title: complete ? "测评已完成" : "草稿已保存" }); const next = this.data.detail.students[this.data.index + 1]; if (complete && next) setTimeout(() => wx.redirectTo({ url: `/pages/assessment-form/index?roundId=${this.data.roundId}&studentId=${next.id}&index=${this.data.index + 1}` }), 350); else setTimeout(() => wx.navigateBack(), 350); } finally { this.setData({ saving: false }); } }
});

