const api = require("../../utils/api");
Page({
  data: { id: "", topics: [], selected: [], form: { name: "", ageGroup: "", classType: "REGULAR", objectivesText: "", description: "", sortOrder: 0, active: true }, saving: false },
  async onLoad(options) { try { const [meta, rows] = await Promise.all([api.call("getTrainingMeta"), api.call("listCurriculums")]); const topics = Object.keys(meta.trainingTopics).map((key) => ({ key, name: meta.trainingTopics[key] })); let form = this.data.form, selected = []; if (options.id) { const row = rows.find((item) => item.id === options.id); if (!row) throw new Error("训练大纲不存在"); form = { ...row, objectivesText: (row.objectives || []).join("、") }; selected = row.trainingTopics || []; } this.setData({ id: options.id || "", topics: topics.map((item) => ({ ...item, checked: selected.includes(item.key) })), selected, form }); } catch (error) { wx.showToast({ title: error.message || "加载失败", icon: "none" }); } },
  field(event) { this.setData({ [`form.${event.currentTarget.dataset.key}`]: event.detail.value }); }, type(event) { this.setData({ "form.classType": event.detail.value ? "ELITE" : "REGULAR" }); },
  topics(event) { const selected = event.detail.value; this.setData({ selected, topics: this.data.topics.map((item) => ({ ...item, checked: selected.includes(item.key) })) }); },
  async save() { this.setData({ saving: true }); try { await api.call("saveCurriculum", { curriculum: { ...this.data.form, id: this.data.id || undefined, sortOrder: Number(this.data.form.sortOrder || 0), objectives: String(this.data.form.objectivesText).split(/[、，,\n]+/).filter(Boolean), trainingTopics: this.data.selected } }); wx.showToast({ title: "训练大纲已保存" }); setTimeout(() => wx.navigateBack(), 400); } finally { this.setData({ saving: false }); } },
  changeStatus() { const active = this.data.form.active === false; wx.showModal({ title: active ? "恢复训练大纲" : "停用训练大纲", content: active ? "恢复后教练可以再次查看。" : "停用后教练不再看到该大纲，历史数据仍会保留。", success: async (result) => { if (!result.confirm) return; await api.call("setCurriculumStatus", { id: this.data.id, active }); this.setData({ "form.active": active }); wx.showToast({ title: active ? "已恢复" : "已停用" }); } }); }
});
