const api = require("../../utils/api");
Page({
  data: { id: "", role: "parent", order: null, loading: true, formMode: "", paymentMethods: [], methodIndex: 0, form: { amount: "", transactionRef: "", remark: "", lessonAdjustment: "", reason: "" }, saving: false },
  onLoad(options) { this.setData({ id: options.id || "" }); }, onShow() { if (this.data.id) this.load(); },
  async load() { const [context, meta, order] = await Promise.all([api.call("getContext"), api.call("getFinanceMeta"), api.call("getOrder", { id: this.data.id })]); const paymentMethods = Object.keys(meta.paymentMethods).map((key) => ({ key, name: meta.paymentMethods[key] })); this.setData({ role: context.user.role, paymentMethods, order, loading: false, form: { amount: String(order.outstandingAmount || ""), transactionRef: "", remark: "", lessonAdjustment: "", reason: "" } }); },
  openPayment() { this.setData({ formMode: "PAYMENT", "form.amount": String(this.data.order.outstandingAmount || "") }); }, openRefund() { const refundable = Number(this.data.order.paidAmount || 0) - Number(this.data.order.refundedAmount || 0); this.setData({ formMode: "REFUND", "form.amount": String(refundable), "form.lessonAdjustment": "" }); }, close() { if (!this.data.saving) this.setData({ formMode: "" }); }, field(event) { this.setData({ [`form.${event.currentTarget.dataset.key}`]: event.detail.value }); }, method(event) { this.setData({ methodIndex: Number(event.detail.value) }); },
  async submitPayment() { const method = this.data.paymentMethods[this.data.methodIndex] || {}; this.setData({ saving: true }); try { await api.call("recordPayment", { orderId: this.data.id, amount: Number(this.data.form.amount), paymentMethod: method.key, transactionRef: this.data.form.transactionRef, idempotencyKey: this.data.form.transactionRef || `${this.data.id}-${Date.now()}`, remark: this.data.form.remark }); wx.showToast({ title: "收款已登记" }); this.setData({ formMode: "" }); this.load(); } finally { this.setData({ saving: false }); } },
  async submitRefund() { if (!this.data.form.reason.trim()) return wx.showToast({ title: "请填写退款原因", icon: "none" }); this.setData({ saving: true }); try { await api.call("refundOrder", { orderId: this.data.id, amount: Number(this.data.form.amount), lessonAdjustment: Number(this.data.form.lessonAdjustment || 0), reason: this.data.form.reason }); wx.showToast({ title: "退款已登记" }); this.setData({ formMode: "" }); this.load(); } finally { this.setData({ saving: false }); } },
  cancelOrder() { wx.showModal({ title: "取消订单", editable: true, placeholderText: "请输入取消原因", success: async (result) => { if (!result.confirm) return; await api.call("cancelOrder", { id: this.data.id, reason: result.content }); wx.showToast({ title: "订单已取消" }); this.load(); } }); }
});
