const api = require("../../utils/api");
const categoryOptions = [{ key: "overall", name: "综合能力" }, { key: "TECHNICAL", name: "技术" }, { key: "TACTICAL", name: "战术" }, { key: "ATHLETIC", name: "运动能力" }, { key: "MATCH", name: "比赛能力" }, { key: "DEVELOPMENT", name: "训练表现" }];

Page({
  data: { studentId: "", profile: null, loading: true, error: "", categoryOptions, categoryIndex: 0, trendLimit: 6, role: "parent" },
  onLoad(options) { this.setData({ studentId: options.studentId || options.id || "" }); },
  onShow() { if (this.data.studentId) this.load(); },
  async load() { this.setData({ loading: true, error: "" }); try { const [context, raw] = await Promise.all([api.call("getContext"), api.call("getGrowthProfile", { studentId: this.data.studentId })]); const profile = { ...raw, student: { ...raw.student, initial: raw.student.name ? raw.student.name[0] : "学", classNamesText: (raw.student.classNames || []).join(" · ") }, latestAssessment: raw.latestAssessment ? { ...raw.latestAssessment, strengthsText: (raw.latestAssessment.strengths || []).join("、"), developmentAreasText: (raw.latestAssessment.developmentAreas || []).join("、") } : null }; this.setData({ profile, role: context.user.role, loading: false }, () => this.drawCharts()); } catch (error) { this.setData({ loading: false, error: "成长档案加载失败" }); } },
  category(event) { this.setData({ categoryIndex: Number(event.detail.value) }, () => this.drawTrend()); },
  limit(event) { this.setData({ trendLimit: Number(event.currentTarget.dataset.limit) }, () => this.drawTrend()); },
  drawCharts() { this.drawTrend(); this.drawRadar(); },
  drawTrend() { if (!wx.createCanvasContext || !this.data.profile) return; const ctx = wx.createCanvasContext("trendCanvas", this), key = this.data.categoryOptions[this.data.categoryIndex].key, rows = this.data.profile.trends.slice(-this.data.trendLimit), width = 320, height = 180, pad = 30; ctx.clearRect(0, 0, width, height); ctx.setStrokeStyle("#dfe5ee"); ctx.setLineWidth(1); for (let i = 1; i <= 5; i += 1) { const y = height - pad - (i - 1) * (height - pad * 2) / 4; ctx.beginPath(); ctx.moveTo(pad, y); ctx.lineTo(width - pad, y); ctx.stroke(); } if (rows.length) { ctx.setStrokeStyle("#12643b"); ctx.setLineWidth(3); ctx.beginPath(); rows.forEach((row, index) => { const x = rows.length === 1 ? width / 2 : pad + index * (width - pad * 2) / (rows.length - 1), value = Number(row[key] || 0), y = height - pad - (value - 1) * (height - pad * 2) / 4; if (!index) ctx.moveTo(x, y); else ctx.lineTo(x, y); ctx.setFillStyle("#12643b"); ctx.fillText(`${value}`, x - 6, y - 8); ctx.setFillStyle("#728095"); ctx.fillText(row.label, x - 14, height - 8); }); ctx.stroke(); } ctx.draw(); },
  drawRadar() { if (!wx.createCanvasContext || !this.data.profile || !this.data.profile.latestAssessment) return; const ctx = wx.createCanvasContext("radarCanvas", this), rows = this.data.profile.comparisons, cx = 160, cy = 105, radius = 72; ctx.clearRect(0, 0, 320, 220); for (let level = 1; level <= 5; level += 1) { ctx.beginPath(); rows.forEach((row, index) => { const angle = -Math.PI / 2 + index * Math.PI * 2 / rows.length, r = radius * level / 5, x = cx + Math.cos(angle) * r, y = cy + Math.sin(angle) * r; if (!index) ctx.moveTo(x, y); else ctx.lineTo(x, y); }); ctx.closePath(); ctx.setStrokeStyle("#dfe5ee"); ctx.stroke(); } ctx.beginPath(); rows.forEach((row, index) => { const angle = -Math.PI / 2 + index * Math.PI * 2 / rows.length, r = radius * Number(row.score || 0) / 5, x = cx + Math.cos(angle) * r, y = cy + Math.sin(angle) * r; if (!index) ctx.moveTo(x, y); else ctx.lineTo(x, y); const lx = cx + Math.cos(angle) * (radius + 24), ly = cy + Math.sin(angle) * (radius + 24); ctx.setFillStyle("#526173"); ctx.fillText(row.name, lx - 16, ly + 4); }); ctx.closePath(); ctx.setFillStyle("rgba(18,100,59,.18)"); ctx.fill(); ctx.setStrokeStyle("#12643b"); ctx.setLineWidth(2); ctx.stroke(); ctx.draw(); },
  assessments() { wx.navigateTo({ url: `/pages/assessment-rounds/index?studentId=${this.data.studentId}` }); },
  match() { wx.navigateTo({ url: `/pages/match-form/index?studentId=${this.data.studentId}` }); }
});
