const CATEGORIES = {
  TECHNICAL: "技术", TACTICAL: "战术", ATHLETIC: "运动能力", MATCH: "比赛能力", DEVELOPMENT: "训练表现"
};
const SCORE_LABELS = { 1: "需要重点培养", 2: "正在建立", 3: "基本掌握", 4: "表现良好", 5: "表现突出" };
const METRICS = {
  TECHNICAL: [["DRIBBLE_TOUCH", "球感"], ["DRIBBLING", "带球"], ["PASSING", "传球"], ["RECEIVING", "接球"], ["SHOOTING", "射门"], ["ONE_V_ONE_ATTACK", "1V1进攻"], ["ONE_V_ONE_DEFENSE", "1V1防守"], ["WEAK_FOOT", "弱势脚使用"]],
  TACTICAL: [["OFF_BALL_MOVEMENT", "无球跑动"], ["SPATIAL_AWARENESS", "空间意识"], ["ATTACK_DECISION", "进攻选择"], ["DEFENSIVE_POSITIONING", "防守站位"], ["TRANSITION", "攻防转换"], ["TEAM_PLAY", "团队配合"]],
  ATHLETIC: [["COORDINATION", "协调性"], ["AGILITY", "灵敏性"], ["SPEED", "速度表现"], ["BALANCE", "平衡能力"], ["ENDURANCE", "耐力表现"]],
  MATCH: [["MATCH_ENGAGEMENT", "比赛投入度"], ["EXECUTION", "执行能力"], ["DUEL_DECISION", "对抗处理"], ["CHANCE_CREATION", "机会创造"], ["DEFENSIVE_CONTRIBUTION", "防守贡献"], ["TEAMWORK", "团队合作"]],
  DEVELOPMENT: [["FOCUS", "训练专注"], ["MOTIVATION", "训练积极性"], ["LEARNING", "学习理解"], ["TEAMWORK", "团队合作"], ["DISCIPLINE", "纪律执行"]]
};
const DAILY_TAGS = ["积极主动", "控球表现好", "1V1表现积极", "传球意识好", "比赛投入", "需要加强专注", "需要提高弱势脚", "需要提高防守意识"];
const HANDLED = new Set(["getGrowthMeta", "listAssessmentTemplates", "saveAssessmentTemplate", "listAssessmentRounds", "createAssessmentRound", "getAssessmentRound", "savePlayerAssessment", "publishAssessmentRound", "getGrowthProfile", "getSessionEvaluationRoster", "saveTrainingEvaluation", "batchAddTrainingTag", "saveMatchRecord", "saveGrowthEvent", "getEliteGrowthSummary"]);

function uid(prefix) { return `${prefix}${Date.now()}${Math.floor(Math.random() * 1000)}`; }
function round(value) { return Math.round(Number(value || 0) * 10) / 10; }
function dimensionsFor(categories, weights) { return categories.flatMap((category) => METRICS[category].map(([metricKey, metricName]) => ({ category, metricKey, metricName, weight: weights[category], enabled: true }))); }
function defaultTemplates() {
  return [
    { id: "at-u56", name: "南联 U5-U6 成长测评", ageGroup: "U5-U6", assessmentType: "STAGE", categoryWeights: { TECHNICAL: 35, TACTICAL: 10, ATHLETIC: 25, MATCH: 10, DEVELOPMENT: 20 }, dimensions: dimensionsFor(["TECHNICAL", "TACTICAL", "ATHLETIC", "MATCH", "DEVELOPMENT"], { TECHNICAL: 35, TACTICAL: 10, ATHLETIC: 25, MATCH: 10, DEVELOPMENT: 20 }), active: true, createdAt: "2026-01-01 09:00", updatedAt: "2026-01-01 09:00" },
    { id: "at-u78", name: "南联 U7-U8 成长测评", ageGroup: "U7-U8", assessmentType: "STAGE", categoryWeights: { TECHNICAL: 35, TACTICAL: 20, ATHLETIC: 20, MATCH: 15, DEVELOPMENT: 10 }, dimensions: dimensionsFor(Object.keys(CATEGORIES), { TECHNICAL: 35, TACTICAL: 20, ATHLETIC: 20, MATCH: 15, DEVELOPMENT: 10 }), active: true, createdAt: "2026-01-01 09:00", updatedAt: "2026-01-01 09:00" }
  ];
}
function scoreSnapshot(base) {
  return Object.keys(METRICS).flatMap((category, categoryIndex) => METRICS[category].map(([metricKey, metricName], index) => ({ category, metricKey, metricName, score: Math.max(1, Math.min(5, round(base + ((index + categoryIndex) % 3 - 1) * 0.2))) })));
}
function calculate(template, scores) {
  const categoryScores = {};
  Object.keys(CATEGORIES).forEach((category) => { const rows = scores.filter((item) => item.category === category); if (rows.length) categoryScores[category] = round(rows.reduce((sum, item) => sum + Number(item.score), 0) / rows.length); });
  const weights = template.categoryWeights || {}; let weighted = 0, totalWeight = 0;
  Object.keys(categoryScores).forEach((category) => { const weight = Number(weights[category] || 1); weighted += categoryScores[category] * weight; totalWeight += weight; });
  return { categoryScores, overallScore: round(totalWeight ? weighted / totalWeight : 0) };
}
function seed(data) {
  const templates = defaultTemplates(); const template = templates[1];
  const stages = [["pa-wxm-1", "2026春季第一阶段测评", "2026-03-20", 3.1], ["pa-wxm-2", "2026春季第二阶段测评", "2026-06-20", 3.5], ["pa-wxm-3", "2026暑期阶段测评", "2026-08-18", 3.9]];
  const playerAssessments = stages.map(([id, assessmentName, assessmentDate, base], index) => { const scores = scoreSnapshot(base); const computed = calculate(template, scores); return { id, roundId: `ar-wxm-${index + 1}`, studentId: "s-growth", classId: "cu8advanced", assessmentTemplateId: template.id, assessmentType: "STAGE", assessmentName, assessmentDate, scores, ...computed, strengths: index === 0 ? ["球感", "训练积极性"] : ["带球", "1V1进攻", "空间意识"], developmentAreas: ["接球前观察", "弱势脚使用"], coachComment: "持续进步，训练中开始主动观察队友位置。", coachMessage: "保持热爱，下一阶段继续大胆使用弱势脚。", status: "COMPLETED", visibility: "PARENT_VISIBLE", published: true, assessedBy: "coach1", assessedByName: "游导", revision: 1, createdAt: `${assessmentDate} 18:00`, updatedAt: `${assessmentDate} 18:00` }; });
  return {
    assessmentTemplates: templates,
    assessmentRounds: stages.map(([id, name, date], index) => ({ id: `ar-wxm-${index + 1}`, name, classId: "cu8advanced", ageGroup: "U7-U8", assessmentTemplateId: template.id, assessmentDate: date, coachId: "coach1", coachName: "游导", status: "COMPLETED", publishedAt: `${date} 19:00`, createdAt: `${date} 09:00`, updatedAt: `${date} 19:00` })),
    playerAssessments,
    playerGrowthEvents: [
      { id: "ge-wxm-1", studentId: "s-growth", eventType: "CLASS_CHANGE", sourceId: "cu8advanced", title: "加入U8基础班", description: "开始系统训练", eventDate: "2025-05-10", visibility: "PARENT_VISIBLE", createdBy: "admin", createdAt: "2025-05-10 10:00" },
      { id: "ge-wxm-2", studentId: "s-growth", eventType: "ELITE_PROMOTION", sourceId: "c1516", title: "进入U8精英队", description: "经教练推荐与管理员审核进入精英队", eventDate: "2026-08-20", visibility: "PARENT_VISIBLE", createdBy: "admin", createdAt: "2026-08-20 10:00" }
    ],
    playerMatchRecords: [
      { id: "mr-wxm-1", studentId: "s-growth", matchDate: "2026-07-12", opponent: "温州青训联队", teamName: "南联U8", position: "中场", minutesPlayed: 45, goals: 0, assists: 1, coachRating: 4, coachComment: "无球接应积极，攻防转换稳定。", visibility: "PARENT_VISIBLE", createdBy: "coach1", createdAt: "2026-07-12 18:00" },
      { id: "mr-wxm-2", studentId: "s-growth", matchDate: "2026-08-10", opponent: "永嘉校园联队", teamName: "南联U8", position: "边锋", minutesPlayed: 50, goals: 1, assists: 0, coachRating: 4, coachComment: "敢于一对一突破，回防意识仍需加强。", visibility: "PARENT_VISIBLE", createdBy: "coach1", createdAt: "2026-08-10 18:00" }
    ],
    feedback: [
      { id: "f-wxm-1", sessionId: "se1", studentId: "s-growth", evaluationType: "DAILY", trainingStatus: 4, highlights: "控球节奏稳定", developmentAreas: "加强弱势脚", coachName: "游导", rating: 4, tags: ["控球表现好"], content: "主动要球，处理球更加从容。", visibility: "PARENT_VISIBLE", createdAt: "2026-08-06 18:00" },
      { id: "f-wxm-2", sessionId: "se1", studentId: "s-growth", evaluationType: "DAILY", trainingStatus: 4, highlights: "1V1突破积极", developmentAreas: "抬头观察", coachName: "游导", rating: 4, tags: ["1V1表现积极"], content: "突破后的传球选择有进步。", visibility: "PARENT_VISIBLE", createdAt: "2026-08-13 18:00" },
      { id: "f-wxm-3", sessionId: "se1", studentId: "s-growth", evaluationType: "DAILY", trainingStatus: 5, highlights: "比赛投入", developmentAreas: "防守站位", coachName: "游导", rating: 5, tags: ["积极主动", "比赛投入"], content: "训练专注，能够主动提醒队友。", visibility: "PARENT_VISIBLE", createdAt: "2026-08-20 18:00" }
    ]
  };
}
function ensure(data) {
  const demo = seed(data);
  if (!Array.isArray(data.assessmentTemplates)) data.assessmentTemplates = demo.assessmentTemplates;
  if (!Array.isArray(data.assessmentRounds)) data.assessmentRounds = demo.assessmentRounds;
  if (!Array.isArray(data.playerAssessments)) data.playerAssessments = demo.playerAssessments;
  if (!Array.isArray(data.playerGrowthEvents)) data.playerGrowthEvents = demo.playerGrowthEvents;
  if (!Array.isArray(data.playerMatchRecords)) data.playerMatchRecords = demo.playerMatchRecords;
  if (!Array.isArray(data.feedback)) data.feedback = [];
  demo.feedback.forEach((item) => { if (!data.feedback.some((row) => row.id === item.id)) data.feedback.push(item); });
}
function canStudent(ctx, studentId) { return ctx.role === "admin" || ctx.canAccessStudent(studentId); }
function canClass(ctx, classId) { return ctx.role === "admin" || (ctx.role === "coach" && ctx.canAccessClass(classId)); }
function visible(item, role) { return role !== "parent" || item.visibility !== "STAFF_ONLY"; }
function growthStudentView(student) {
  if (!student) return null;
  const value = { ...student };
  delete value.idCard;
  delete value.idCardNumber;
  delete value.privateProfile;
  return value;
}
function decorateAssessment(data, item) { const template = data.assessmentTemplates.find((row) => row.id === item.assessmentTemplateId) || {}; return { ...item, templateName: template.name, categoryRows: Object.keys(CATEGORIES).map((key) => ({ key, name: CATEGORIES[key], score: item.categoryScores[key] || 0 })), statusLabel: item.status === "COMPLETED" ? "已完成" : "草稿" }; }
function monthStats(data, studentId) { const month = new Date().toISOString().slice(0, 7); const rows = data.attendance.filter((item) => item.studentId === studentId && String(item.date).slice(0, 7) === month); return { total: rows.length, present: rows.filter((item) => item.status === "present").length, leave: rows.filter((item) => item.status === "leave").length, absent: rows.filter((item) => item.status === "absent").length }; }
function profile(data, studentId, ctx) {
  if (!canStudent(ctx, studentId)) throw new Error("无权查看该球员成长档案"); const student = data.students.find((item) => item.id === studentId); if (!student) throw new Error("学员不存在");
  const classIds = (data.classMembers || []).filter((item) => item.studentId === studentId && item.status === "ACTIVE").map((item) => item.classId); const classes = data.classes.filter((item) => classIds.includes(item.id));
  const assessments = data.playerAssessments.filter((item) => item.studentId === studentId && (ctx.role !== "parent" || item.published && visible(item, ctx.role))).sort((a, b) => String(a.assessmentDate).localeCompare(String(b.assessmentDate))).map((item) => decorateAssessment(data, item));
  const latest = assessments[assessments.length - 1] || null, previous = assessments[assessments.length - 2] || null;
  const comparisons = Object.keys(CATEGORIES).map((key) => { const score = latest ? Number(latest.categoryScores[key] || 0) : 0, before = previous ? Number(previous.categoryScores[key] || 0) : 0, delta = round(score - before); return { key, name: CATEGORIES[key], score, delta, direction: delta > 0 ? "up" : delta < 0 ? "down" : "flat", deltaText: delta > 0 ? `↑ ${delta}` : delta < 0 ? `↓ ${Math.abs(delta)}` : "→" }; });
  const feedback = data.feedback.filter((item) => item.studentId === studentId && visible(item, ctx.role)).sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt)));
  const matches = data.playerMatchRecords.filter((item) => item.studentId === studentId && visible(item, ctx.role)).sort((a, b) => String(b.matchDate).localeCompare(String(a.matchDate)));
  const generated = [...assessments.map((item) => ({ id: `timeline-${item.id}`, studentId, eventType: "ASSESSMENT", sourceId: item.id, title: item.assessmentName, description: `综合能力 ${item.overallScore}`, eventDate: item.assessmentDate, visibility: item.visibility })), ...feedback.map((item) => ({ id: `timeline-${item.id}`, eventType: "TRAINING", sourceId: item.id, title: "训练评价", description: item.content, eventDate: String(item.createdAt).slice(0, 10), visibility: item.visibility })), ...matches.map((item) => ({ id: `timeline-${item.id}`, eventType: "MATCH", sourceId: item.id, title: `${item.teamName} vs ${item.opponent}`, description: item.coachComment, eventDate: item.matchDate, visibility: item.visibility }))];
  const events = [...data.playerGrowthEvents.filter((item) => item.studentId === studentId && visible(item, ctx.role)), ...generated].sort((a, b) => String(b.eventDate).localeCompare(String(a.eventDate))).slice(0, 30);
  const joined = (data.classMembers || []).filter((item) => item.studentId === studentId).map((item) => item.joinedAt).filter(Boolean).sort()[0] || student.registrationDate || ""; const months = joined ? Math.max(0, Math.floor((Date.now() - new Date(joined.replace(/-/g, "/")).getTime()) / 2629800000)) : 0;
  const recentAttendance = data.attendance.filter((item) => item.studentId === studentId).sort((a, b) => String(b.date).localeCompare(String(a.date)))[0];
  return { student: { ...growthStudentView(student), classNames: classes.map((item) => item.name), trainingDuration: `${Math.floor(months / 12)}年${months % 12}个月`, latestTrainingDate: recentAttendance ? recentAttendance.date : "暂无" }, attendance: monthStats(data, studentId), latestAssessment: latest, previousAssessment: previous, comparisons, assessments, trends: assessments.slice(-6).map((item) => ({ date: item.assessmentDate, label: String(item.assessmentDate).slice(5), overall: item.overallScore, ...item.categoryScores })), feedback: feedback.slice(0, 10), matches: matches.slice(0, 10), events };
}

async function call(action, input, ctx) {
  const { data, role } = ctx; ensure(data);
  if (action === "getGrowthMeta") return { categories: CATEGORIES, scoreLabels: SCORE_LABELS, metrics: METRICS, dailyTags: DAILY_TAGS, templates: data.assessmentTemplates.filter((item) => item.active) };
  if (action === "listAssessmentTemplates") { if (!['admin', 'coach'].includes(role)) throw new Error("无权查看测评模板"); return data.assessmentTemplates; }
  if (action === "saveAssessmentTemplate") { if (role !== "admin") throw new Error("仅管理员可维护测评模板"); const item = { ...input.template, id: input.template.id || uid("at"), active: input.template.active !== false, updatedAt: ctx.stamp() }; if (!item.name || !item.ageGroup || !item.dimensions || !item.dimensions.length) throw new Error("测评模板信息不完整"); const index = data.assessmentTemplates.findIndex((row) => row.id === item.id); if (index >= 0) data.assessmentTemplates[index] = { ...data.assessmentTemplates[index], ...item }; else data.assessmentTemplates.push({ ...item, createdAt: ctx.stamp() }); ctx.audit("saveAssessmentTemplate", "assessmentTemplate", item.id, item.name); ctx.save(); return { id: item.id }; }
  if (action === "listAssessmentRounds") { if (role === "parent") throw new Error("家长不能进入测评工作台"); return data.assessmentRounds.filter((item) => canClass(ctx, item.classId)).map((item) => { const expected = (data.classMembers || []).filter((row) => row.classId === item.classId && row.status === "ACTIVE").length, completed = data.playerAssessments.filter((row) => row.roundId === item.id && row.status === "COMPLETED").length; return { ...item, expected, completed, progressText: `${completed} / ${expected}` }; }).sort((a, b) => String(b.assessmentDate).localeCompare(String(a.assessmentDate))); }
  if (action === "createAssessmentRound") { if (role !== "admin") throw new Error("仅管理员可创建阶段测评"); const template = data.assessmentTemplates.find((item) => item.id === input.assessmentTemplateId && item.active); if (!template) throw new Error("请选择有效测评模板"); const item = { id: uid("ar"), name: String(input.name || "").trim(), classId: input.classId, ageGroup: input.ageGroup || template.ageGroup, assessmentTemplateId: template.id, assessmentDate: input.assessmentDate, coachId: input.coachId || "", coachName: input.coachName || "", status: "DRAFT", createdAt: ctx.stamp(), updatedAt: ctx.stamp() }; if (!item.name || !item.classId || !item.assessmentDate) throw new Error("阶段测评信息不完整"); data.assessmentRounds.push(item); ctx.audit("createAssessmentRound", "assessmentRound", item.id, item.name); ctx.save(); return { id: item.id }; }
  if (action === "getAssessmentRound") { if (role === "parent") throw new Error("家长不能进入测评工作台"); const item = data.assessmentRounds.find((row) => row.id === input.id); if (!item || !canClass(ctx, item.classId)) throw new Error("无权查看该阶段测评"); const members = (data.classMembers || []).filter((row) => row.classId === item.classId && row.status === "ACTIVE"); return { ...item, template: data.assessmentTemplates.find((row) => row.id === item.assessmentTemplateId), students: members.map((member) => { const student = data.students.find((row) => row.id === member.studentId); const assessment = data.playerAssessments.find((row) => row.roundId === item.id && row.studentId === member.studentId); return { ...growthStudentView(student), assessmentId: assessment ? assessment.id : "", assessmentStatus: assessment ? assessment.status : "NOT_STARTED" }; }), completed: data.playerAssessments.filter((row) => row.roundId === item.id && row.status === "COMPLETED").length, expected: members.length }; }
  if (action === "savePlayerAssessment") { if (!['admin', 'coach'].includes(role)) throw new Error("无权填写测评"); const roundItem = data.assessmentRounds.find((item) => item.id === input.roundId); if (!roundItem || !canClass(ctx, roundItem.classId)) throw new Error("无权评价该班球员"); if (!(data.classMembers || []).some((item) => item.classId === roundItem.classId && item.studentId === input.studentId && item.status === "ACTIVE")) throw new Error("只能评价本班正式成员"); const template = data.assessmentTemplates.find((item) => item.id === roundItem.assessmentTemplateId); const validKeys = new Set(template.dimensions.filter((item) => item.enabled).map((item) => item.metricKey)); const scores = (input.scores || []).filter((item) => validKeys.has(item.metricKey)).map((item) => ({ ...item, score: Math.max(1, Math.min(5, Number(item.score))) })); if (!scores.length) throw new Error("请至少填写一项评分"); const computed = calculate(template, scores); const existing = data.playerAssessments.find((item) => item.roundId === roundItem.id && item.studentId === input.studentId); const now = ctx.stamp(); const item = { id: existing ? existing.id : uid("pa"), roundId: roundItem.id, studentId: input.studentId, classId: roundItem.classId, assessmentTemplateId: template.id, assessmentType: "STAGE", assessmentName: roundItem.name, assessmentDate: roundItem.assessmentDate, scores, ...computed, strengths: input.strengths || [], developmentAreas: input.developmentAreas || [], coachComment: String(input.coachComment || ""), coachMessage: String(input.coachMessage || ""), mediaAttachments: input.mediaAttachments || [], status: input.complete ? "COMPLETED" : "DRAFT", visibility: input.visibility || "STAFF_ONLY", published: false, assessedBy: ctx.userId, assessedByName: ctx.userName, revision: existing ? Number(existing.revision || 1) + 1 : 1, createdAt: existing ? existing.createdAt : now, updatedAt: now, updatedBy: ctx.userId }; if (existing) Object.assign(existing, item); else data.playerAssessments.push(item); ctx.audit(existing ? "updatePlayerAssessment" : "savePlayerAssessment", "playerAssessment", item.id, { studentId: item.studentId, roundId: item.roundId, revision: item.revision }); ctx.save(); return { id: item.id, overallScore: item.overallScore, status: item.status }; }
  if (action === "publishAssessmentRound") { if (role !== "admin") throw new Error("仅管理员可发布测评"); const item = data.assessmentRounds.find((row) => row.id === input.id); if (!item) throw new Error("阶段测评不存在"); const expected = (data.classMembers || []).filter((row) => row.classId === item.classId && row.status === "ACTIVE").length, rows = data.playerAssessments.filter((row) => row.roundId === item.id && row.status === "COMPLETED"); if (!expected || rows.length < expected) throw new Error(`尚未完成全部测评（${rows.length}/${expected}）`); item.status = "COMPLETED"; item.publishedAt = ctx.stamp(); item.updatedAt = item.publishedAt; item.publishedBy = ctx.userId; rows.forEach((row) => { row.published = true; if (row.visibility !== "STAFF_ONLY") row.visibility = "PARENT_VISIBLE"; row.updatedAt = item.updatedAt; }); ctx.audit("publishAssessmentRound", "assessmentRound", item.id, `${rows.length}名球员`); ctx.save(); return { ok: true, published: rows.length }; }
  if (action === "getGrowthProfile") return profile(data, input.studentId, ctx);
  if (action === "getSessionEvaluationRoster") { if (!['admin', 'coach'].includes(role)) throw new Error("无权评价训练"); const session = data.sessions.find((item) => item.id === input.sessionId); if (!session || !canClass(ctx, session.classId)) throw new Error("无权评价该课程"); const ids = (data.classMembers || []).filter((item) => item.classId === session.classId && item.status === "ACTIVE").map((item) => item.studentId); return { session, students: data.students.filter((item) => ids.includes(item.id)).map((student) => ({ ...growthStudentView(student), evaluation: data.feedback.find((item) => item.sessionId === session.id && item.studentId === student.id) || null })) }; }
  if (action === "saveTrainingEvaluation") { if (!['admin', 'coach'].includes(role)) throw new Error("无权填写训练评价"); const session = data.sessions.find((item) => item.id === input.sessionId); if (!session || !canClass(ctx, session.classId) || !(data.classMembers || []).some((item) => item.classId === session.classId && item.studentId === input.studentId && item.status === "ACTIVE")) throw new Error("只能评价授权班级正式成员"); const existing = data.feedback.find((item) => item.sessionId === session.id && item.studentId === input.studentId); const item = { id: existing ? existing.id : uid("f"), sessionId: session.id, studentId: input.studentId, evaluationType: "DAILY", trainingStatus: Math.max(1, Math.min(5, Number(input.trainingStatus || 3))), highlights: String(input.highlights || ""), developmentAreas: String(input.developmentAreas || ""), coachName: ctx.userName, rating: Math.max(1, Math.min(5, Number(input.trainingStatus || 3))), tags: input.tags || [], content: String(input.coachComment || ""), visibility: input.visibility || "STAFF_ONLY", mediaAttachments: input.mediaAttachments || [], createdAt: existing ? existing.createdAt : ctx.stamp(), updatedAt: ctx.stamp(), updatedBy: ctx.userId }; if (existing) Object.assign(existing, item); else data.feedback.push(item); ctx.audit(existing ? "updateTrainingEvaluation" : "saveTrainingEvaluation", "feedback", item.id, { studentId: item.studentId, sessionId: item.sessionId, visibility: item.visibility }); ctx.save(); return { id: item.id }; }
  if (action === "batchAddTrainingTag") { if (!['admin', 'coach'].includes(role)) throw new Error("无权批量评价"); const roster = await call("getSessionEvaluationRoster", { sessionId: input.sessionId }, ctx); const allowed = new Set(roster.students.map((item) => item.id)); const tag = String(input.tag || "").trim(); if (!tag) throw new Error("请选择评价标签"); (input.studentIds || []).forEach((studentId) => { if (!allowed.has(studentId)) throw new Error("批量名单包含非本班成员"); const existing = data.feedback.find((item) => item.sessionId === input.sessionId && item.studentId === studentId); if (existing) existing.tags = [...new Set([...(existing.tags || []), tag])]; else data.feedback.push({ id: uid("f"), sessionId: input.sessionId, studentId, evaluationType: "DAILY", trainingStatus: 3, highlights: "", developmentAreas: "", coachName: ctx.userName, rating: 3, tags: [tag], content: "", visibility: "STAFF_ONLY", createdAt: ctx.stamp(), updatedAt: ctx.stamp(), updatedBy: ctx.userId }); }); ctx.audit("batchAddTrainingTag", "session", input.sessionId, { studentIds: input.studentIds || [], tag }); ctx.save(); return { count: (input.studentIds || []).length }; }
  if (action === "saveMatchRecord") { if (!['admin', 'coach'].includes(role) || !canStudent(ctx, input.studentId)) throw new Error("无权创建比赛记录"); const item = { ...input, id: input.id || uid("mr"), goals: Number(input.goals || 0), assists: Number(input.assists || 0), minutesPlayed: Number(input.minutesPlayed || 0), coachRating: Math.max(1, Math.min(5, Number(input.coachRating || 3))), visibility: input.visibility || "STAFF_ONLY", createdBy: ctx.userId, createdAt: ctx.stamp(), updatedAt: ctx.stamp() }; if (!item.matchDate || !item.opponent || !item.teamName) throw new Error("比赛记录信息不完整"); data.playerMatchRecords.push(item); ctx.audit("saveMatchRecord", "playerMatchRecord", item.id, { studentId: item.studentId, matchDate: item.matchDate }); ctx.save(); return { id: item.id }; }
  if (action === "saveGrowthEvent") { if (role !== "admin") throw new Error("仅管理员可创建成长事件"); const item = { ...input, id: uid("ge"), visibility: input.visibility || "STAFF_ONLY", createdBy: ctx.userId, createdAt: ctx.stamp() }; if (!item.studentId || !item.title || !item.eventDate) throw new Error("成长事件信息不完整"); data.playerGrowthEvents.push(item); ctx.audit("saveGrowthEvent", "playerGrowthEvent", item.id, { studentId: item.studentId, visibility: item.visibility }); ctx.save(); return { id: item.id }; }
  if (action === "getEliteGrowthSummary") { if (!['admin', 'coach'].includes(role)) throw new Error("无权查看选拔参考"); const result = profile(data, input.studentId, ctx); return { latestAssessment: result.latestAssessment, trends: result.trends, recentFeedback: result.feedback.slice(0, 3), matches: result.matches.slice(0, 3), attendance: result.attendance }; }
  throw new Error(`未实现成长操作：${action}`);
}

module.exports = { CATEGORIES, SCORE_LABELS, METRICS, DAILY_TAGS, handles: (action) => HANDLED.has(action), ensure, calculate, call };
