const ACTIONS = new Set(["getLeagueDashboard", "getLeagueMeta", "createLeague", "createLeagueSeason", "generateLeagueRounds", "updateLeagueRound", "saveLeagueTeam", "saveLeagueTeamMember", "saveExternalPlayer", "registerSeasonTeam", "generateRoundRobin", "getLeagueRound", "getLeagueTeamRoster", "saveMatchSquad", "saveLeagueMatch", "getLeagueStandings"]);
const SUNDAY = 0;

function isoWeek(value) {
  const date = new Date(`${value}T12:00:00Z`), day = date.getUTCDay() || 7;
  date.setUTCDate(date.getUTCDate() + 4 - day);
  const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
  return Math.ceil((((date - yearStart) / 86400000) + 1) / 7);
}
function dateText(date) { return date.toISOString().slice(0, 10); }
function sundays(startDate, endDate) {
  const start = new Date(`${startDate}T12:00:00Z`), end = new Date(`${endDate}T12:00:00Z`);
  while (start.getUTCDay() !== SUNDAY) start.setUTCDate(start.getUTCDate() + 1);
  const result = [];
  while (start <= end) { result.push(dateText(start)); start.setUTCDate(start.getUTCDate() + 7); }
  return result;
}
function weekConfig(season, date, roundNo) {
  const weekNumber = isoWeek(date), odd = season.scheduleMode === "SEASON_ROUND" ? roundNo % 2 === 1 : weekNumber % 2 === 1;
  return { weekNumber, weekType: odd ? "ODD" : "EVEN", birthYears: [...(odd ? season.oddWeekBirthYears : season.evenWeekBirthYears)] };
}
function pairs(ids) { const rows = []; for (let i = 0; i < ids.length; i += 1) for (let j = i + 1; j < ids.length; j += 1) rows.push([ids[i], ids[j]]); return rows; }
function sameYears(a, b) { return [...(a || [])].sort().join(",") === [...(b || [])].sort().join(","); }

function ensure(data) {
  data.tournaments = data.tournaments || [];
  data.leagues = data.leagues || [];
  data.leagueSeasons = data.leagueSeasons || [];
  data.leagueRounds = data.leagueRounds || [];
  data.teams = data.teams || [];
  data.teamMembers = data.teamMembers || [];
  data.seasonTeams = data.seasonTeams || [];
  data.externalPlayers = data.externalPlayers || [];
  data.matches = data.matches || [];
  data.matchSquads = data.matchSquads || [];
  if (data.leagues.some((item) => item.id === "lg-sunday")) return;
  const league = { id: "lg-sunday", tournamentId: "t-growth", name: "南联周日成长联赛", competitionType: "LEAGUE", leagueType: "GROWTH_LEAGUE", recurringRule: "SUNDAY_ALTERNATING_WEEK", oddWeekAgeGroups: [2017, 2018], evenWeekAgeGroups: [2015, 2016], defaultMatchDay: 0, active: true, createdAt: "2026-08-01 10:00" };
  data.leagues.push(league); data.tournaments.push({ id: "t-growth", name: league.name, competitionType: "LEAGUE", leagueId: league.id, active: true });
  const season = { id: "ls-2026-autumn", leagueId: league.id, name: "南联周日成长联赛 · 2026秋季赛季", startDate: "2026-08-23", endDate: "2026-10-11", status: "ACTIVE", scheduleMode: "CALENDAR_WEEK", oddWeekBirthYears: [2017, 2018], evenWeekBirthYears: [2015, 2016], defaultVenueIds: ["三江南联球场"], standingsEnabled: false, pointsRule: { win: 3, draw: 1, loss: 0 }, description: "以成长和比赛体验为核心的固定周日赛事", createdBy: "admin", createdAt: "2026-08-01 10:10", updatedAt: "2026-08-01 10:10" };
  data.leagueSeasons.push(season);
  sundays(season.startDate, season.endDate).forEach((date, index) => data.leagueRounds.push({ id: `lr${index + 1}`, seasonId: season.id, roundNo: index + 1, date, ...weekConfig(season, date, index + 1), venueId: "三江南联球场", status: "SCHEDULED", remark: "", createdAt: "2026-08-01 10:20" }));
  data.teams.push(
    { id: "tm-nl17", name: "南联2017队", organizationType: "INTERNAL", organizationName: "永嘉南联", birthYearGroup: [2017, 2018], classId: "c1718", coachUserId: "coach1", coachName: "游导" },
    { id: "tm-nl18", name: "南联2018队", organizationType: "INTERNAL", organizationName: "永嘉南联", birthYearGroup: [2017, 2018], classId: "c1718", coachUserId: "coach1", coachName: "游导" },
    { id: "tm-nl16", name: "南联2016精英队", organizationType: "INTERNAL", organizationName: "永嘉南联", birthYearGroup: [2015, 2016], classId: "c1516", coachUserId: "coach1", coachName: "游导" },
    { id: "tm-ob17", name: "瓯北中心2017队", organizationType: "EXTERNAL", organizationName: "瓯北中心小学", birthYearGroup: [2017, 2018], contactName: "林老师", contactMobile: "13800001717", coachName: "林教练" },
    { id: "tm-xx18", name: "XX小学2018队", organizationType: "EXTERNAL", organizationName: "XX小学", birthYearGroup: [2017, 2018], contactName: "陈老师", contactMobile: "13800001818", coachName: "陈教练" },
    { id: "tm-club16", name: "XX俱乐部2016队", organizationType: "EXTERNAL", organizationName: "XX足球俱乐部", birthYearGroup: [2015, 2016], contactName: "张教练", contactMobile: "13800001616", coachName: "张教练" }
  );
  data.teamMembers.push({ id: "tmem1", teamId: "tm-nl17", studentId: "s-growth", memberType: "INTERNAL_STUDENT", jerseyNumber: 10, status: "ACTIVE" }, { id: "tmem2", teamId: "tm-nl17", studentId: "s1", memberType: "INTERNAL_STUDENT", jerseyNumber: 7, status: "ACTIVE" }, { id: "tmem3", teamId: "tm-nl18", studentId: "s2", memberType: "INTERNAL_STUDENT", jerseyNumber: 8, status: "ACTIVE" }, { id: "tmem4", teamId: "tm-nl16", studentId: "s3", memberType: "INTERNAL_STUDENT", jerseyNumber: 9, status: "ACTIVE" });
  data.externalPlayers.push({ id: "ep1", teamId: "tm-ob17", name: "外队球员甲", gender: "男", birthYear: 2017, jerseyNumber: 9, guardianName: "", guardianMobile: "", remark: "", createdAt: "2026-08-02 10:00" }, { id: "ep2", teamId: "tm-xx18", name: "外队球员乙", gender: "男", birthYear: 2018, jerseyNumber: 10, guardianName: "", guardianMobile: "", remark: "", createdAt: "2026-08-02 10:00" }, { id: "ep3", teamId: "tm-club16", name: "外队球员丙", gender: "女", birthYear: 2016, jerseyNumber: 8, guardianName: "", guardianMobile: "", remark: "", createdAt: "2026-08-02 10:00" });
  data.teams.forEach((team) => data.seasonTeams.push({ id: `st-${team.id}`, seasonId: season.id, teamId: team.id, birthYearGroup: team.birthYearGroup, status: "ACTIVE", overrideReason: "" }));
  const round = data.leagueRounds[0], teamIds = ["tm-nl17", "tm-nl18", "tm-ob17", "tm-xx18"];
  pairs(teamIds).forEach((pair, index) => data.matches.push({ id: `lm${index + 1}`, tournamentId: "t-growth", leagueId: league.id, seasonId: season.id, roundId: round.id, homeTeamId: pair[0], awayTeamId: pair[1], matchDate: round.date, startTime: `${String(9 + index).padStart(2, "0")}:00`, venueId: round.venueId, status: "SCHEDULED", homeScore: null, awayScore: null, lessonDeduction: 0, createdAt: "2026-08-03 10:00" }));
}

function teamView(team, role) { if (!team) return {}; const copy = { ...team }; if (role === "parent") { delete copy.contactMobile; delete copy.coachMobile; delete copy.contactName; } return copy; }
function standings(data, seasonId) {
  const season = data.leagueSeasons.find((item) => item.id === seasonId), rule = (season || {}).pointsRule || { win: 3, draw: 1, loss: 0 };
  const map = {}; (data.seasonTeams || []).filter((item) => item.seasonId === seasonId).forEach((item) => { const team = data.teams.find((row) => row.id === item.teamId); map[item.teamId] = { teamId: item.teamId, teamName: (team || {}).name || "", played: 0, win: 0, draw: 0, loss: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 }; });
  data.matches.filter((item) => item.seasonId === seasonId && item.status === "FINISHED").forEach((match) => { const home = map[match.homeTeamId], away = map[match.awayTeamId]; if (!home || !away) return; const hs = Number(match.homeScore), as = Number(match.awayScore); home.played += 1; away.played += 1; home.goalsFor += hs; home.goalsAgainst += as; away.goalsFor += as; away.goalsAgainst += hs; if (hs > as) { home.win += 1; away.loss += 1; home.points += Number(rule.win); away.points += Number(rule.loss); } else if (hs < as) { away.win += 1; home.loss += 1; away.points += Number(rule.win); home.points += Number(rule.loss); } else { home.draw += 1; away.draw += 1; home.points += Number(rule.draw); away.points += Number(rule.draw); } });
  return Object.values(map).map((item) => ({ ...item, goalDifference: item.goalsFor - item.goalsAgainst })).sort((a, b) => b.points - a.points || b.goalDifference - a.goalDifference);
}

async function call(action, input, ctx) {
  const { data, role } = ctx; ensure(data);
  const admin = () => { if (role !== "admin") throw new Error("仅管理员可执行该操作"); };
  const staff = () => { if (!["admin", "coach"].includes(role)) throw new Error("无赛事管理权限"); };
  if (action === "getLeagueMeta") return { scheduleModes: [{ key: "CALENDAR_WEEK", name: "按自然周" }, { key: "SEASON_ROUND", name: "按赛季轮次" }], statuses: ["DRAFT", "ACTIVE", "FINISHED", "ARCHIVED"], roundStatuses: ["SCHEDULED", "POSTPONED", "CANCELLED", "FINISHED"], organizationTypes: ["INTERNAL", "EXTERNAL"] };
  if (action === "getLeagueDashboard") { const league = data.leagues.find((item) => item.active), season = data.leagueSeasons.find((item) => item.leagueId === (league || {}).id && item.status === "ACTIVE") || data.leagueSeasons[0]; const rounds = data.leagueRounds.filter((item) => item.seasonId === (season || {}).id).sort((a, b) => a.date.localeCompare(b.date)); const nextRound = rounds.find((item) => item.status !== "CANCELLED" && item.date >= (input.today || ctx.stamp().slice(0, 10))) || rounds[0]; let matches = data.matches.filter((item) => item.roundId === (nextRound || {}).id).sort((a, b) => a.startTime.localeCompare(b.startTime)); if (role === "parent") { if (input.studentId && !ctx.canAccessStudent(input.studentId)) throw new Error("无权访问该学员"); const own = new Set(input.studentId ? [input.studentId] : (ctx.canAccessStudent ? data.students.filter((item) => ctx.canAccessStudent(item.id)).map((item) => item.id) : [])); const matchIds = new Set(data.matchSquads.filter((item) => item.memberType === "INTERNAL_STUDENT" && own.has(item.studentId)).map((item) => item.matchId)); matches = matches.filter((item) => matchIds.has(item.id)); } return { league, season, nextRound, rounds, teams: data.seasonTeams.filter((item) => item.seasonId === (season || {}).id).map((item) => teamView(data.teams.find((row) => row.id === item.teamId), role)), matches: matches.map((item) => ({ ...item, homeTeam: teamView(data.teams.find((row) => row.id === item.homeTeamId), role), awayTeam: teamView(data.teams.find((row) => row.id === item.awayTeamId), role) })), standings: standings(data, (season || {}).id), standingsVisible: role !== "parent" || Boolean((season || {}).standingsEnabled) }; }
  if (action === "createLeague") { admin(); const item = { ...input, id: ctx.uid("lg"), competitionType: "LEAGUE", active: input.active !== false, createdAt: ctx.stamp() }; data.leagues.push(item); data.tournaments.push({ id: ctx.uid("t"), name: item.name, competitionType: "LEAGUE", leagueId: item.id, active: true }); ctx.audit("createLeague", "league", item.id, item.name); ctx.save(); return { id: item.id }; }
  if (action === "createLeagueSeason") { admin(); const league = data.leagues.find((item) => item.id === input.leagueId); if (!league || !input.name || !input.startDate || !input.endDate) throw new Error("赛季信息不完整"); const item = { ...input, id: ctx.uid("ls"), scheduleMode: input.scheduleMode || "CALENDAR_WEEK", oddWeekBirthYears: (input.oddWeekBirthYears || league.oddWeekAgeGroups).map(Number), evenWeekBirthYears: (input.evenWeekBirthYears || league.evenWeekAgeGroups).map(Number), standingsEnabled: Boolean(input.standingsEnabled), pointsRule: input.pointsRule || { win: 3, draw: 1, loss: 0 }, status: input.status || "DRAFT", createdBy: ctx.userId, createdAt: ctx.stamp(), updatedAt: ctx.stamp() }; data.leagueSeasons.push(item); ctx.audit("createLeagueSeason", "leagueSeason", item.id, item.name); ctx.save(); return { id: item.id }; }
  if (action === "generateLeagueRounds") { admin(); const season = data.leagueSeasons.find((item) => item.id === input.seasonId); if (!season) throw new Error("赛季不存在"); const existing = data.leagueRounds.filter((item) => item.seasonId === season.id); if (existing.length && !input.confirmRegenerate) return { confirmationRequired: true, existing: existing.length }; const dates = sundays(season.startDate, season.endDate); const created = []; dates.forEach((date, index) => { if (data.leagueRounds.some((item) => item.seasonId === season.id && item.date === date)) return; const item = { id: ctx.uid("lr"), seasonId: season.id, roundNo: index + 1, date, ...weekConfig(season, date, index + 1), venueId: (season.defaultVenueIds || [])[0] || "", status: "SCHEDULED", remark: "", createdAt: ctx.stamp() }; data.leagueRounds.push(item); created.push(item); }); ctx.audit("generateLeagueRounds", "leagueSeason", season.id, `${created.length}轮`); ctx.save(); return { created: created.length, rounds: created }; }
  if (action === "updateLeagueRound") { admin(); const item = data.leagueRounds.find((row) => row.id === input.id); if (!item) throw new Error("轮次不存在"); const previousDate = item.date; if (input.status === "POSTPONED" && input.date && input.date !== item.date) { item.originalDate = item.originalDate || item.date; item.newDate = input.date; item.date = input.date; } Object.assign(item, { birthYears: input.birthYears || item.birthYears, venueId: input.venueId === undefined ? item.venueId : input.venueId, status: input.status || item.status, remark: input.remark === undefined ? item.remark : input.remark, updatedAt: ctx.stamp() }); data.matches.filter((match) => match.roundId === item.id && previousDate !== item.date).forEach((match) => { match.matchDate = item.date; match.updatedAt = ctx.stamp(); }); ctx.audit(input.status === "POSTPONED" ? "postponeLeagueRound" : input.status === "CANCELLED" ? "cancelLeagueRound" : "updateLeagueRound", "leagueRound", item.id, { previousDate, date: item.date, birthYears: item.birthYears }); ctx.save(); return { ok: true }; }
  if (action === "saveLeagueTeam") { admin(); const item = { ...input, id: input.id || ctx.uid("tm"), birthYearGroup: (input.birthYearGroup || []).map(Number), organizationType: input.organizationType || "EXTERNAL", updatedAt: ctx.stamp() }; if (!item.name || !item.birthYearGroup.length) throw new Error("球队信息不完整"); const old = data.teams.find((row) => row.id === item.id); if (old) Object.assign(old, item); else data.teams.push({ ...item, createdAt: ctx.stamp() }); ctx.audit(old ? "updateLeagueTeam" : "createLeagueTeam", "team", item.id, item.name); ctx.save(); return { id: item.id }; }
  if (action === "saveLeagueTeamMember") { staff(); const team = data.teams.find((item) => item.id === input.teamId), student = data.students.find((item) => item.id === input.studentId); if (!team || team.organizationType !== "INTERNAL" || !student) throw new Error("内部球队成员信息无效"); if (role === "coach" && team.coachUserId !== ctx.userId) throw new Error("只能管理自己负责的球队"); const old = data.teamMembers.find((item) => item.teamId === team.id && item.studentId === student.id && item.status === "ACTIVE"); if (old) return { id: old.id, duplicate: true }; const item = { id: ctx.uid("tmem"), teamId: team.id, studentId: student.id, memberType: "INTERNAL_STUDENT", jerseyNumber: input.jerseyNumber || "", status: "ACTIVE", createdAt: ctx.stamp() }; data.teamMembers.push(item); ctx.audit("saveLeagueTeamMember", "teamMember", item.id, { teamId: team.id, studentId: student.id }); ctx.save(); return { id: item.id }; }
  if (action === "saveExternalPlayer") { admin(); const team = data.teams.find((item) => item.id === input.teamId); if (!team || team.organizationType !== "EXTERNAL") throw new Error("只能为外部球队录入外部球员"); const item = { ...input, id: input.id || ctx.uid("ep"), birthYear: Number(input.birthYear), createdAt: ctx.stamp(), updatedAt: ctx.stamp() }; if (!item.name || !item.birthYear) throw new Error("球员必要信息不完整"); data.externalPlayers.push(item); ctx.audit("createExternalPlayer", "externalPlayer", item.id, { teamId: item.teamId, name: item.name }); ctx.save(); return { id: item.id }; }
  if (action === "registerSeasonTeam") { admin(); const team = data.teams.find((item) => item.id === input.teamId), target = (input.birthYearGroup || team.birthYearGroup || []).map(Number); if (!sameYears(team.birthYearGroup, target) && !input.overrideReason) return { confirmationRequired: true, message: "球队年龄组与赛季报名组别不一致" }; const item = { id: ctx.uid("st"), seasonId: input.seasonId, teamId: team.id, birthYearGroup: target, status: "ACTIVE", overrideReason: input.overrideReason || "", createdAt: ctx.stamp() }; data.seasonTeams.push(item); ctx.audit("registerSeasonTeam", "seasonTeam", item.id, item); ctx.save(); return { id: item.id }; }
  if (action === "generateRoundRobin") { admin(); const round = data.leagueRounds.find((item) => item.id === input.roundId); const eligible = data.seasonTeams.filter((item) => item.seasonId === round.seasonId && (sameYears(item.birthYearGroup, round.birthYears) || (input.teamIds || []).includes(item.teamId))).map((item) => item.teamId); const ids = input.teamIds && input.teamIds.length ? input.teamIds : eligible; const created = []; pairs(ids).forEach((pair, index) => { if (data.matches.some((item) => item.roundId === round.id && ((item.homeTeamId === pair[0] && item.awayTeamId === pair[1]) || (item.homeTeamId === pair[1] && item.awayTeamId === pair[0])))) return; const item = { id: ctx.uid("lm"), tournamentId: (data.leagues.find((item) => item.id === (data.leagueSeasons.find((row) => row.id === round.seasonId) || {}).leagueId) || {}).tournamentId || "t-growth", leagueId: (data.leagueSeasons.find((row) => row.id === round.seasonId) || {}).leagueId, seasonId: round.seasonId, roundId: round.id, homeTeamId: pair[0], awayTeamId: pair[1], matchDate: round.date, startTime: `${String(9 + index).padStart(2, "0")}:00`, venueId: round.venueId, status: "SCHEDULED", homeScore: null, awayScore: null, lessonDeduction: 0, createdAt: ctx.stamp() }; data.matches.push(item); created.push(item); }); ctx.audit("generateRoundRobin", "leagueRound", round.id, `${created.length}场`); ctx.save(); return { created: created.length }; }
  if (action === "getLeagueRound") { const round = data.leagueRounds.find((item) => item.id === input.id); if (!round) throw new Error("轮次不存在"); let roundMatches = data.matches.filter((item) => item.roundId === round.id); if (role === "parent") { if (input.studentId && !ctx.canAccessStudent(input.studentId)) throw new Error("无权访问该学员"); const own = new Set(input.studentId ? [input.studentId] : data.students.filter((item) => ctx.canAccessStudent(item.id)).map((item) => item.id)), allowed = new Set(data.matchSquads.filter((item) => item.memberType === "INTERNAL_STUDENT" && own.has(item.studentId)).map((item) => item.matchId)); roundMatches = roundMatches.filter((item) => allowed.has(item.id)); } return { round, teams: data.seasonTeams.filter((item) => item.seasonId === round.seasonId && sameYears(item.birthYearGroup, round.birthYears)).map((item) => teamView(data.teams.find((row) => row.id === item.teamId), role)), matches: roundMatches.sort((a, b) => a.startTime.localeCompare(b.startTime)).map((item) => ({ ...item, homeTeam: teamView(data.teams.find((row) => row.id === item.homeTeamId), role), awayTeam: teamView(data.teams.find((row) => row.id === item.awayTeamId), role), squads: role === "parent" ? [] : data.matchSquads.filter((row) => row.matchId === item.id) })) }; }
  if (action === "getLeagueTeamRoster") { staff(); const team = data.teams.find((item) => item.id === input.teamId); if (!team) throw new Error("球队不存在"); const selected = new Set(data.matchSquads.filter((item) => item.matchId === input.matchId && item.teamId === team.id).map((item) => item.studentId || item.externalPlayerId)); const members = team.organizationType === "INTERNAL" ? data.teamMembers.filter((item) => item.teamId === team.id && item.status === "ACTIVE").map((item) => { const student = data.students.find((row) => row.id === item.studentId) || {}; return { ...item, memberId: item.studentId, name: student.name || "", avatarUrl: student.avatarUrl || "", birthDate: student.birthDate || "", initial: student.name ? student.name[0] : "学", memberType: "INTERNAL_STUDENT", selected: selected.has(item.studentId) }; }) : data.externalPlayers.filter((item) => item.teamId === team.id).map((item) => ({ ...item, memberId: item.id, avatarUrl: "", initial: item.name ? item.name[0] : "球", memberType: "EXTERNAL_PLAYER", selected: selected.has(item.id) })); return { team: teamView(team, role), members }; }
  if (action === "saveMatchSquad") { staff(); const match = data.matches.find((item) => item.id === input.matchId), team = data.teams.find((item) => item.id === input.teamId); if (!match || !team || ![match.homeTeamId, match.awayTeamId].includes(team.id)) throw new Error("比赛名单信息无效"); if (role === "coach" && (team.organizationType !== "INTERNAL" || team.coachUserId !== ctx.userId)) throw new Error("只能管理自己负责的内部球队"); const next = []; (input.members || []).forEach((member) => { const internal = member.memberType === "INTERNAL_STUDENT"; if (internal === Boolean(member.externalPlayerId) || internal !== Boolean(member.studentId)) throw new Error("名单成员类型与身份不匹配"); if (internal && !data.teamMembers.some((item) => item.teamId === team.id && item.studentId === member.studentId && item.status === "ACTIVE")) throw new Error("内部球员不属于该比赛队"); if (!internal && !(data.externalPlayers || []).some((item) => item.id === member.externalPlayerId && item.teamId === team.id)) throw new Error("外部球员不属于该队"); next.push({ id: ctx.uid("ms"), matchId: match.id, teamId: team.id, memberType: member.memberType, studentId: member.studentId || "", externalPlayerId: member.externalPlayerId || "", jerseyNumber: member.jerseyNumber || "", starter: Boolean(member.starter), position: member.position || "", goals: Number(member.goals || 0), assists: Number(member.assists || 0), status: "ACTIVE", createdAt: ctx.stamp() }); }); data.matchSquads = data.matchSquads.filter((item) => item.matchId !== match.id || item.teamId !== team.id).concat(next); ctx.audit("saveMatchSquad", "match", match.id, { teamId: team.id, count: next.length }); ctx.save(); return { added: next.length }; }
  if (action === "saveLeagueMatch") { admin(); const match = data.matches.find((item) => item.id === input.id); if (!match) throw new Error("比赛不存在"); const wasFinished = match.status === "FINISHED"; Object.assign(match, { startTime: input.startTime || match.startTime, venueId: input.venueId || match.venueId, homeScore: Number(input.homeScore), awayScore: Number(input.awayScore), status: input.status || "FINISHED", updatedAt: ctx.stamp(), lessonDeduction: 0 }); if (match.status === "FINISHED") { data.matchSquads.filter((item) => item.matchId === match.id && item.memberType === "INTERNAL_STUDENT").forEach((squad) => { if (!data.playerMatchRecords.some((item) => item.matchId === match.id && item.studentId === squad.studentId)) { const ownTeam = data.teams.find((item) => item.id === squad.teamId), opponentId = squad.teamId === match.homeTeamId ? match.awayTeamId : match.homeTeamId, opponent = data.teams.find((item) => item.id === opponentId); data.playerMatchRecords.push({ id: ctx.uid("mr"), studentId: squad.studentId, matchId: match.id, matchDate: match.matchDate, opponent: (opponent || {}).name || "", teamName: (ownTeam || {}).name || "南联", position: squad.position || "", minutesPlayed: Number(squad.minutesPlayed || 0), goals: Number(squad.goals || 0), assists: Number(squad.assists || 0), coachRating: Number(squad.coachRating || 3), coachComment: squad.coachComment || "参加南联周日成长联赛", visibility: "PARENT_VISIBLE", source: "GROWTH_LEAGUE", createdBy: ctx.userId, createdAt: ctx.stamp(), updatedAt: ctx.stamp() }); data.playerGrowthEvents.push({ id: ctx.uid("ge"), studentId: squad.studentId, eventType: "MATCH", sourceId: match.id, title: "参加南联周日成长联赛", description: `${(ownTeam || {}).name || "南联"} 对阵 ${(opponent || {}).name || "对手"}`, eventDate: match.matchDate, visibility: "PARENT_VISIBLE", createdBy: ctx.userId, createdAt: ctx.stamp() }); } }); } ctx.audit(wasFinished ? "updateLeagueScore" : "finishLeagueMatch", "match", match.id, { homeScore: match.homeScore, awayScore: match.awayScore }); ctx.save(); return { ok: true }; }
  if (action === "getLeagueStandings") { const season = data.leagueSeasons.find((item) => item.id === input.seasonId); if (role === "parent" && !season.standingsEnabled) throw new Error("本赛季未对家长开放积分榜"); return standings(data, input.seasonId); }
  throw new Error("未知成长联赛操作");
}

module.exports = { ACTIONS, handles: (action) => ACTIONS.has(action), ensure, call, isoWeek, sundays, weekConfig, standings };
