const ACTIONS = new Set(["getTrainingMeta", "getResearchDashboard", "listCurriculums", "saveCurriculum", "archiveCurriculum", "listWeeklyTrainingPlans", "getWeeklyTrainingPlan", "saveWeeklyTrainingPlan", "confirmWeeklyTrainingPlan", "saveSessionTrainingInfo", "getSessionTrainingInfo", "getSessionTrainingPlan", "getCoachWorkbench", "getTrainingHistory"]);
const TRAINING_TOPICS = { BALL_MASTERY: "球感", DRIBBLING: "带球", PASSING: "传球", RECEIVING: "接球", SHOOTING: "射门", ONE_V_ONE_ATTACK: "1V1进攻", ONE_V_ONE_DEFENSE: "1V1防守", TWO_V_ONE: "2V1", SPATIAL_AWARENESS: "空间意识", TRANSITION: "攻防转换", TEAM_PLAY: "团队配合", COORDINATION: "协调", MATCH_PLAY: "比赛" };
const STATUS_LABELS = { DRAFT: "草稿", CONFIRMED: "已确认", COMPLETED: "已完成" };
function ensure(data) {
  data.curriculums = data.curriculums || [];
  const curriculums = [
    { id: "cur-u6-simple", name: "南联U5-U6训练大纲", ageGroup: "U5-U6", classType: "REGULAR", objectives: ["建立足球兴趣", "发展球感与协调"], trainingTopics: ["BALL_MASTERY", "COORDINATION", "DRIBBLING", "SHOOTING", "ONE_V_ONE_ATTACK", "MATCH_PLAY"], description: "球感、协调、带球、射门、简单1V1和游戏化比赛。", active: true },
    { id: "cur-u8-simple", name: "南联U7-U8训练大纲", ageGroup: "U7-U8", classType: "REGULAR", objectives: ["建立控球基础", "培养主动进攻与空间意识"], trainingTopics: ["BALL_MASTERY", "DRIBBLING", "PASSING", "RECEIVING", "ONE_V_ONE_ATTACK", "TWO_V_ONE", "SHOOTING", "SPATIAL_AWARENESS", "TRANSITION", "MATCH_PLAY"], description: "控球、带球、传接球、1V1、2V1、射门、空间意识、攻防转换和小场比赛。", active: true },
    { id: "cur-u8-elite-simple", name: "南联U8精英队训练大纲", ageGroup: "U8", classType: "ELITE", objectives: ["提高比赛决策", "发展团队配合与位置意识"], trainingTopics: ["ONE_V_ONE_ATTACK", "TRANSITION", "SPATIAL_AWARENESS", "TEAM_PLAY", "MATCH_PLAY"], description: "高强度1V1、攻防转换、比赛决策、团队配合、位置意识和比赛应用。", active: true }
  ];
  curriculums.forEach((item) => { if (!data.curriculums.some((row) => row.id === item.id)) data.curriculums.push({ ...item, createdBy: "admin", createdAt: "2026-08-21 09:00", updatedAt: "2026-08-21 09:00" }); });
  data.weeklyTrainingPlans = data.weeklyTrainingPlans || [];
  const plans = [
    { id: "wp-u8-demo", classId: "cu8advanced", coachId: "coach1", coachName: "游导", weekStart: "2026-08-24", weekEnd: "2026-08-30", mainTheme: "1V1进攻", themeKey: "ONE_V_ONE_ATTACK", trainingFocus: ["变向", "加速", "突破后的射门", "比赛中主动使用1V1"], curriculumId: "cur-u8-simple", status: "CONFIRMED", meetingNote: "周二增加带球变向训练，周四增加2V1应用。", updatedBy: "admin" },
    { id: "wp-u7-demo", classId: "cu7base", coachId: "coach2", coachName: "王蒋生", weekStart: "2026-08-24", weekEnd: "2026-08-30", mainTheme: "传接球", themeKey: "PASSING", trainingFocus: ["支撑脚", "传球力量", "接球前观察"], curriculumId: "cur-u8-simple", status: "DRAFT", meetingNote: "", updatedBy: "coach2" },
    { id: "wp-elite-demo", classId: "c1516", coachId: "coach1", coachName: "游导", weekStart: "2026-08-24", weekEnd: "2026-08-30", mainTheme: "攻防转换", themeKey: "TRANSITION", trainingFocus: ["丢球后反抢", "获得球权后向前", "位置协同"], curriculumId: "cur-u8-elite-simple", status: "CONFIRMED", meetingNote: "精英队提高对抗强度。", updatedBy: "admin" }
  ];
  plans.forEach((item) => { if (!data.weeklyTrainingPlans.some((row) => row.id === item.id)) data.weeklyTrainingPlans.push({ ...item, createdAt: "2026-08-21 09:00", updatedAt: "2026-08-21 09:00" }); });
  const sessions = [
    { id: "se-simple-tue", classId: "cu8advanced", title: "U8基础班周二训练", date: "2026-08-25", weekday: "周二", time: "18:00-19:30", venue: "瓯北中心小学", coachName: "游导", coachUserId: "coach1", focus: "1V1变向突破", trainingTheme: "1V1变向突破", trainingThemeKey: "ONE_V_ONE_ATTACK", trainingFocus: ["变向", "加速"], trainingNote: "根据人数增加2V2比赛。", weeklyTrainingPlanId: "wp-u8-demo", capacity: 20, status: "published", enrollmentMode: "fixed" },
    { id: "se-simple-thu", classId: "cu8advanced", title: "U8基础班周四训练", date: "2026-08-27", weekday: "周四", time: "18:00-19:30", venue: "瓯北中心小学", coachName: "游导", coachUserId: "coach1", focus: "1V1+射门", trainingTheme: "1V1+射门", trainingThemeKey: "ONE_V_ONE_ATTACK", trainingFocus: ["突破后的加速", "突破后的射门"], trainingNote: "", weeklyTrainingPlanId: "wp-u8-demo", capacity: 20, status: "published", enrollmentMode: "fixed" }
  ];
  sessions.forEach((item) => { if (!data.sessions.some((row) => row.id === item.id)) data.sessions.push(item); });
  const sunday = (data.matches || []).find((item) => item.leagueId === "lg-sunday"); if (sunday) { sunday.trainingPurpose = sunday.trainingPurpose || "MATCH_APPLICATION"; sunday.observationFocus = sunday.observationFocus || "比赛中主动使用1V1"; sunday.weeklyTrainingPlanId = sunday.weeklyTrainingPlanId || "wp-u8-demo"; }
}
function staff(ctx) { if (!["admin", "coach"].includes(ctx.role)) throw new Error("仅教练团队可进入训练管理"); }
function canClass(ctx, classId) { return ctx.role === "admin" || ctx.canAccessClass(classId); }
function curriculumView(item) { return { ...item, topicNames: (item.trainingTopics || []).map((key) => TRAINING_TOPICS[key] || key) }; }
function planView(data, item) { const clubClass = data.classes.find((row) => row.id === item.classId) || {}, curriculum = data.curriculums.find((row) => row.id === item.curriculumId) || {}; return { ...item, className: clubClass.name || "", ageGroup: clubClass.ageGroup || "", curriculumName: curriculum.name || "", statusLabel: STATUS_LABELS[item.status] || item.status }; }
async function call(action, input, ctx) { const { data } = ctx; ensure(data);
  if (action === "getTrainingMeta") return { trainingTopics: TRAINING_TOPICS, statuses: STATUS_LABELS };
  if (action === "listCurriculums") { staff(ctx); return data.curriculums.filter((item) => ctx.role === "admin" || item.active).map(curriculumView); }
  if (action === "saveCurriculum") { if (ctx.role !== "admin") throw new Error("仅管理员可维护训练大纲"); const raw = input.curriculum || {}, old = raw.id && data.curriculums.find((item) => item.id === raw.id), item = { ...raw, id: raw.id || ctx.uid("cur"), name: String(raw.name || "").trim(), ageGroup: String(raw.ageGroup || ""), classType: raw.classType === "ELITE" ? "ELITE" : "REGULAR", objectives: raw.objectives || [], trainingTopics: raw.trainingTopics || [], description: String(raw.description || ""), active: raw.active !== false, createdBy: old ? old.createdBy : ctx.userId, createdAt: old ? old.createdAt : ctx.stamp(), updatedAt: ctx.stamp() }; if (!item.name || !item.ageGroup || !item.trainingTopics.length) throw new Error("训练大纲信息不完整"); if (old) Object.assign(old, item); else data.curriculums.push(item); ctx.audit("SAVE_CURRICULUM", "curriculum", item.id, { name: item.name }); ctx.save(); return { id: item.id }; }
  if (action === "archiveCurriculum") { if (ctx.role !== "admin") throw new Error("仅管理员可归档训练大纲"); const item = data.curriculums.find((row) => row.id === input.id); if (!item) throw new Error("训练大纲不存在"); item.active = false; item.updatedAt = ctx.stamp(); ctx.audit("ARCHIVE_CURRICULUM", "curriculum", item.id, {}); ctx.save(); return { ok: true }; }
  if (action === "listWeeklyTrainingPlans") { staff(ctx); let rows = data.weeklyTrainingPlans.filter((item) => item.classId && canClass(ctx, item.classId)); if (input.classId) rows = rows.filter((item) => item.classId === input.classId); if (input.coachId) rows = rows.filter((item) => item.coachId === input.coachId); if (input.status) rows = rows.filter((item) => item.status === input.status); return rows.sort((a, b) => String(b.weekStart).localeCompare(String(a.weekStart))).map((item) => planView(data, item)); }
  if (action === "getWeeklyTrainingPlan") { staff(ctx); const item = data.weeklyTrainingPlans.find((row) => row.id === input.id); if (!item || !canClass(ctx, item.classId)) throw new Error("无权查看该周训练计划"); return planView(data, item); }
  if (action === "saveWeeklyTrainingPlan") { staff(ctx); const raw = input.plan || {}, old = raw.id && data.weeklyTrainingPlans.find((item) => item.id === raw.id); if (old && !canClass(ctx, old.classId)) throw new Error("无权修改该周训练计划"); const classId = raw.classId || (old || {}).classId; if (!canClass(ctx, classId)) throw new Error("只能制定自己负责班级的周计划"); const item = { ...old, ...raw, id: raw.id || ctx.uid("wp"), classId, coachId: raw.coachId || (old || {}).coachId || ctx.userId, coachName: raw.coachName || (old || {}).coachName || ctx.userName, weekStart: raw.weekStart || "", weekEnd: raw.weekEnd || "", mainTheme: String(raw.mainTheme || "").trim(), themeKey: raw.themeKey || "", trainingFocus: raw.trainingFocus || [], curriculumId: raw.curriculumId || "", status: raw.status || (old || {}).status || "DRAFT", meetingNote: String(raw.meetingNote || ""), updatedBy: ctx.userId, updatedAt: ctx.stamp(), createdAt: old ? old.createdAt : ctx.stamp() }; if (!item.weekStart || !item.weekEnd || !item.mainTheme || !item.trainingFocus.length) throw new Error("周训练计划信息不完整"); if (old) Object.assign(old, item); else data.weeklyTrainingPlans.push(item); ctx.audit("SAVE_WEEKLY_TRAINING_PLAN", "weeklyTrainingPlan", item.id, { classId, status: item.status }); ctx.save(); return { id: item.id }; }
  if (action === "confirmWeeklyTrainingPlan") { staff(ctx); const item = data.weeklyTrainingPlans.find((row) => row.id === input.id); if (!item || !canClass(ctx, item.classId)) throw new Error("无权确认该周训练计划"); item.status = input.completed ? "COMPLETED" : "CONFIRMED"; item.meetingNote = input.meetingNote === undefined ? item.meetingNote : String(input.meetingNote); item.updatedBy = ctx.userId; item.updatedAt = ctx.stamp(); ctx.audit("CONFIRM_WEEKLY_TRAINING_PLAN", "weeklyTrainingPlan", item.id, { status: item.status }); ctx.save(); return { ok: true, status: item.status }; }
  if (action === "saveSessionTrainingInfo") { staff(ctx); const session = data.sessions.find((item) => item.id === input.sessionId); if (!session || !canClass(ctx, session.classId)) throw new Error("无权修改该课程训练信息"); session.trainingTheme = String(input.trainingTheme || "").trim(); session.trainingThemeKey = input.trainingThemeKey || ""; session.trainingFocus = input.trainingFocus || []; session.trainingNote = String(input.trainingNote || ""); session.weeklyTrainingPlanId = input.weeklyTrainingPlanId || session.weeklyTrainingPlanId || ""; if (!session.trainingTheme || !session.trainingFocus.length) throw new Error("请填写训练主题和训练重点"); session.updatedAt = ctx.stamp(); session.updatedBy = ctx.userId; ctx.audit("SAVE_SESSION_TRAINING_INFO", "session", session.id, { trainingTheme: session.trainingTheme }); ctx.save(); return { ok: true }; }
  if (action === "getSessionTrainingInfo" || action === "getSessionTrainingPlan") { const session = data.sessions.find((item) => item.id === input.sessionId); if (!session) throw new Error("课程不存在"); const weekly = data.weeklyTrainingPlans.find((item) => item.id === session.weeklyTrainingPlanId), value = { session: { id: session.id, title: session.title, date: session.date, time: session.time, classId: session.classId }, trainingTheme: session.trainingTheme || session.focus || "", trainingThemeKey: session.trainingThemeKey || "", trainingFocus: session.trainingFocus || [], trainingNote: session.trainingNote || "", weeklyTrainingPlanId: session.weeklyTrainingPlanId || "", weeklyTheme: weekly ? weekly.mainTheme : "", trainingPurpose: session.trainingPurpose || "" }; if (ctx.role === "parent") { if (!ctx.canAccessStudent(input.studentId)) throw new Error("无权查看该孩子训练信息"); delete value.trainingNote; return value; } staff(ctx); if (!canClass(ctx, session.classId)) throw new Error("无权查看该课程训练信息"); value.weeklyPlan = weekly ? planView(data, weekly) : null; return value; }
  if (action === "getCoachWorkbench") { staff(ctx); const sessions = data.sessions.filter((item) => canClass(ctx, item.classId)).sort((a, b) => `${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`)).map((session) => { const members = (data.classMembers || []).filter((item) => item.classId === session.classId && item.status === "ACTIVE").length, leaveCount = data.leaveRequests.filter((item) => item.sessionId === session.id && item.status === "approved").length; return { ...session, memberCount: members, leaveCount, trainingTheme: session.trainingTheme || session.focus || "待填写", trainingFocusText: (session.trainingFocus || []).join(" / ") }; }); return { date: input.date || ctx.stamp().slice(0, 10), sessions }; }
  if (action === "getTrainingHistory") { if (!ctx.canAccessStudent(input.studentId)) throw new Error("无权查看训练履历"); const days = Number(input.days || 30), start = new Date(Date.now() - days * 86400000), attendance = data.attendance.filter((item) => item.studentId === input.studentId && item.status === "present"), ids = new Set(attendance.map((item) => item.sessionId)), counts = {}; data.sessions.filter((item) => ids.has(item.id) && new Date(String(item.date).replace(/-/g, "/")) >= start).forEach((item) => { const key = item.trainingThemeKey || item.trainingTheme || item.focus; if (key) counts[key] = (counts[key] || 0) + 1; }); return { days, totalSessions: Object.values(counts).reduce((sum, count) => sum + count, 0), tags: Object.keys(counts).map((key) => ({ key, name: TRAINING_TOPICS[key] || key, count: counts[key] })).sort((a, b) => b.count - a.count) }; }
  if (action === "getResearchDashboard") { staff(ctx); const plans = data.weeklyTrainingPlans.filter((item) => item.classId && canClass(ctx, item.classId)), sessions = data.sessions.filter((item) => canClass(ctx, item.classId)), filled = sessions.filter((item) => item.trainingTheme && (item.trainingFocus || []).length); return { metrics: { curriculums: data.curriculums.filter((item) => item.active).length, weeklyPlans: plans.length, confirmedPlans: plans.filter((item) => item.status === "CONFIRMED").length, sessions: sessions.length, filledSessions: filled.length }, weeklyPlans: plans.map((item) => planView(data, item)) }; }
  throw new Error("未知训练管理操作");
}
module.exports = { ACTIONS, TRAINING_TOPICS, handles: (action) => ACTIONS.has(action), ensure, call };
