const api = require("../../utils/api");

Page({
  data: { loading: true, saving: false, session: null, students: [], studentIndex: 0, sessionId: "", studentId: "", tags: [], tagOptions: [], selectedTags: [], trainingStatus: 3, highlights: "", developmentAreas: "", coachComment: "", visibility: "STAFF_ONLY" },
  async onLoad(options) { this.setData({ sessionId: options.sessionId || "", studentId: options.studentId || "" }); try { const [meta, roster] = await Promise.all([api.call("getGrowthMeta"), api.call("getSessionEvaluationRoster", { sessionId: options.sessionId })]); const studentIndex = Math.max(0, roster.students.findIndex((item) => item.id === this.data.studentId)), student = roster.students[studentIndex] || {}, existing = student.evaluation || {}, selectedTags = existing.tags || []; this.setData({ session: roster.session, students: roster.students, studentIndex, studentId: student.id || "", tags: meta.dailyTags, tagOptions: meta.dailyTags.map((name) => ({ name, checked: selectedTags.includes(name) })), selectedTags, trainingStatus: Number(existing.trainingStatus || existing.rating || 3), highlights: existing.highlights || "", developmentAreas: existing.developmentAreas || "", coachComment: existing.content || "", visibility: existing.visibility || "STAFF_ONLY", loading: false }); } catch (error) { this.setData({ loading: false }); } },
  studentChange(event) { const studentIndex = Number(event.detail.value), student = this.data.students[studentIndex], existing = student.evaluation || {}, selectedTags = existing.tags || []; this.setData({ studentIndex, studentId: student.id, selectedTags, tagOptions: this.data.tags.map((name) => ({ name, checked: selectedTags.includes(name) })), trainingStatus: Number(existing.trainingStatus || existing.rating || 3), highlights: existing.highlights || "", developmentAreas: existing.developmentAreas || "", coachComment: existing.content || "", visibility: existing.visibility || "STAFF_ONLY" }); },
  status(event) { this.setData({ trainingStatus: Number(event.detail.value) }); }, tags(event) { this.setData({ selectedTags: event.detail.value }); }, field(event) { this.setData({ [event.currentTarget.dataset.key]: event.detail.value }); }, visible(event) { this.setData({ visibility: event.detail.value ? "PARENT_VISIBLE" : "STAFF_ONLY" }); },
  async save() { if (this.data.saving) return; if (!this.data.coachComment.trim() && !this.data.highlights.trim()) return wx.showToast({ title: "请填写亮点或评语", icon: "none" }); this.setData({ saving: true }); try { await api.call("saveTrainingEvaluation", { sessionId: this.data.sessionId, studentId: this.data.studentId, trainingStatus: this.data.trainingStatus, tags: this.data.selectedTags, highlights: this.data.highlights, developmentAreas: this.data.developmentAreas, coachComment: this.data.coachComment, visibility: this.data.visibility }); wx.showToast({ title: "训练评价已保存" }); setTimeout(() => wx.navigateBack(), 400); } finally { this.setData({ saving: false }); } }
});
